package com.pengkong.boatrace.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class MlExpectedExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public MlExpectedExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andModelnoIsNull() {
			addCriterion("modelno is null");
			return (Criteria) this;
		}

		public Criteria andModelnoIsNotNull() {
			addCriterion("modelno is not null");
			return (Criteria) this;
		}

		public Criteria andModelnoEqualTo(String value) {
			addCriterion("modelno =", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotEqualTo(String value) {
			addCriterion("modelno <>", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoGreaterThan(String value) {
			addCriterion("modelno >", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoGreaterThanOrEqualTo(String value) {
			addCriterion("modelno >=", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoLessThan(String value) {
			addCriterion("modelno <", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoLessThanOrEqualTo(String value) {
			addCriterion("modelno <=", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoLike(String value) {
			addCriterion("modelno like", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotLike(String value) {
			addCriterion("modelno not like", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoIn(List<String> values) {
			addCriterion("modelno in", values, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotIn(List<String> values) {
			addCriterion("modelno not in", values, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoBetween(String value1, String value2) {
			addCriterion("modelno between", value1, value2, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotBetween(String value1, String value2) {
			addCriterion("modelno not between", value1, value2, "modelno");
			return (Criteria) this;
		}

		public Criteria andYmdIsNull() {
			addCriterion("ymd is null");
			return (Criteria) this;
		}

		public Criteria andYmdIsNotNull() {
			addCriterion("ymd is not null");
			return (Criteria) this;
		}

		public Criteria andYmdEqualTo(String value) {
			addCriterion("ymd =", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotEqualTo(String value) {
			addCriterion("ymd <>", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdGreaterThan(String value) {
			addCriterion("ymd >", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdGreaterThanOrEqualTo(String value) {
			addCriterion("ymd >=", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLessThan(String value) {
			addCriterion("ymd <", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLessThanOrEqualTo(String value) {
			addCriterion("ymd <=", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLike(String value) {
			addCriterion("ymd like", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotLike(String value) {
			addCriterion("ymd not like", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdIn(List<String> values) {
			addCriterion("ymd in", values, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotIn(List<String> values) {
			addCriterion("ymd not in", values, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdBetween(String value1, String value2) {
			addCriterion("ymd between", value1, value2, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotBetween(String value1, String value2) {
			addCriterion("ymd not between", value1, value2, "ymd");
			return (Criteria) this;
		}

		public Criteria andJyocdIsNull() {
			addCriterion("jyocd is null");
			return (Criteria) this;
		}

		public Criteria andJyocdIsNotNull() {
			addCriterion("jyocd is not null");
			return (Criteria) this;
		}

		public Criteria andJyocdEqualTo(String value) {
			addCriterion("jyocd =", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotEqualTo(String value) {
			addCriterion("jyocd <>", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdGreaterThan(String value) {
			addCriterion("jyocd >", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdGreaterThanOrEqualTo(String value) {
			addCriterion("jyocd >=", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLessThan(String value) {
			addCriterion("jyocd <", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLessThanOrEqualTo(String value) {
			addCriterion("jyocd <=", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLike(String value) {
			addCriterion("jyocd like", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotLike(String value) {
			addCriterion("jyocd not like", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdIn(List<String> values) {
			addCriterion("jyocd in", values, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotIn(List<String> values) {
			addCriterion("jyocd not in", values, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdBetween(String value1, String value2) {
			addCriterion("jyocd between", value1, value2, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotBetween(String value1, String value2) {
			addCriterion("jyocd not between", value1, value2, "jyocd");
			return (Criteria) this;
		}

		public Criteria andRacenoIsNull() {
			addCriterion("raceno is null");
			return (Criteria) this;
		}

		public Criteria andRacenoIsNotNull() {
			addCriterion("raceno is not null");
			return (Criteria) this;
		}

		public Criteria andRacenoEqualTo(Short value) {
			addCriterion("raceno =", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotEqualTo(Short value) {
			addCriterion("raceno <>", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoGreaterThan(Short value) {
			addCriterion("raceno >", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoGreaterThanOrEqualTo(Short value) {
			addCriterion("raceno >=", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoLessThan(Short value) {
			addCriterion("raceno <", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoLessThanOrEqualTo(Short value) {
			addCriterion("raceno <=", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoIn(List<Short> values) {
			addCriterion("raceno in", values, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotIn(List<Short> values) {
			addCriterion("raceno not in", values, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoBetween(Short value1, Short value2) {
			addCriterion("raceno between", value1, value2, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotBetween(Short value1, Short value2) {
			addCriterion("raceno not between", value1, value2, "raceno");
			return (Criteria) this;
		}

		public Criteria andProbIsNull() {
			addCriterion("prob is null");
			return (Criteria) this;
		}

		public Criteria andProbIsNotNull() {
			addCriterion("prob is not null");
			return (Criteria) this;
		}

		public Criteria andProbEqualTo(Object value) {
			addCriterion("prob =", value, "prob");
			return (Criteria) this;
		}

		public Criteria andProbNotEqualTo(Object value) {
			addCriterion("prob <>", value, "prob");
			return (Criteria) this;
		}

		public Criteria andProbGreaterThan(Object value) {
			addCriterion("prob >", value, "prob");
			return (Criteria) this;
		}

		public Criteria andProbGreaterThanOrEqualTo(Object value) {
			addCriterion("prob >=", value, "prob");
			return (Criteria) this;
		}

		public Criteria andProbLessThan(Object value) {
			addCriterion("prob <", value, "prob");
			return (Criteria) this;
		}

		public Criteria andProbLessThanOrEqualTo(Object value) {
			addCriterion("prob <=", value, "prob");
			return (Criteria) this;
		}

		public Criteria andProbIn(List<Object> values) {
			addCriterion("prob in", values, "prob");
			return (Criteria) this;
		}

		public Criteria andProbNotIn(List<Object> values) {
			addCriterion("prob not in", values, "prob");
			return (Criteria) this;
		}

		public Criteria andProbBetween(Object value1, Object value2) {
			addCriterion("prob between", value1, value2, "prob");
			return (Criteria) this;
		}

		public Criteria andProbNotBetween(Object value1, Object value2) {
			addCriterion("prob not between", value1, value2, "prob");
			return (Criteria) this;
		}

		public Criteria andBorIsNull() {
			addCriterion("bor is null");
			return (Criteria) this;
		}

		public Criteria andBorIsNotNull() {
			addCriterion("bor is not null");
			return (Criteria) this;
		}

		public Criteria andBorEqualTo(Object value) {
			addCriterion("bor =", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorNotEqualTo(Object value) {
			addCriterion("bor <>", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorGreaterThan(Object value) {
			addCriterion("bor >", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorGreaterThanOrEqualTo(Object value) {
			addCriterion("bor >=", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorLessThan(Object value) {
			addCriterion("bor <", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorLessThanOrEqualTo(Object value) {
			addCriterion("bor <=", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorIn(List<Object> values) {
			addCriterion("bor in", values, "bor");
			return (Criteria) this;
		}

		public Criteria andBorNotIn(List<Object> values) {
			addCriterion("bor not in", values, "bor");
			return (Criteria) this;
		}

		public Criteria andBorBetween(Object value1, Object value2) {
			addCriterion("bor between", value1, value2, "bor");
			return (Criteria) this;
		}

		public Criteria andBorNotBetween(Object value1, Object value2) {
			addCriterion("bor not between", value1, value2, "bor");
			return (Criteria) this;
		}

		public Criteria andBorkIsNull() {
			addCriterion("bork is null");
			return (Criteria) this;
		}

		public Criteria andBorkIsNotNull() {
			addCriterion("bork is not null");
			return (Criteria) this;
		}

		public Criteria andBorkEqualTo(Object value) {
			addCriterion("bork =", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkNotEqualTo(Object value) {
			addCriterion("bork <>", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkGreaterThan(Object value) {
			addCriterion("bork >", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkGreaterThanOrEqualTo(Object value) {
			addCriterion("bork >=", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkLessThan(Object value) {
			addCriterion("bork <", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkLessThanOrEqualTo(Object value) {
			addCriterion("bork <=", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkIn(List<Object> values) {
			addCriterion("bork in", values, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkNotIn(List<Object> values) {
			addCriterion("bork not in", values, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkBetween(Object value1, Object value2) {
			addCriterion("bork between", value1, value2, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkNotBetween(Object value1, Object value2) {
			addCriterion("bork not between", value1, value2, "bork");
			return (Criteria) this;
		}

		public Criteria andRorIsNull() {
			addCriterion("ror is null");
			return (Criteria) this;
		}

		public Criteria andRorIsNotNull() {
			addCriterion("ror is not null");
			return (Criteria) this;
		}

		public Criteria andRorEqualTo(Object value) {
			addCriterion("ror =", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorNotEqualTo(Object value) {
			addCriterion("ror <>", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorGreaterThan(Object value) {
			addCriterion("ror >", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorGreaterThanOrEqualTo(Object value) {
			addCriterion("ror >=", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorLessThan(Object value) {
			addCriterion("ror <", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorLessThanOrEqualTo(Object value) {
			addCriterion("ror <=", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorIn(List<Object> values) {
			addCriterion("ror in", values, "ror");
			return (Criteria) this;
		}

		public Criteria andRorNotIn(List<Object> values) {
			addCriterion("ror not in", values, "ror");
			return (Criteria) this;
		}

		public Criteria andRorBetween(Object value1, Object value2) {
			addCriterion("ror between", value1, value2, "ror");
			return (Criteria) this;
		}

		public Criteria andRorNotBetween(Object value1, Object value2) {
			addCriterion("ror not between", value1, value2, "ror");
			return (Criteria) this;
		}

		public Criteria andRorkIsNull() {
			addCriterion("rork is null");
			return (Criteria) this;
		}

		public Criteria andRorkIsNotNull() {
			addCriterion("rork is not null");
			return (Criteria) this;
		}

		public Criteria andRorkEqualTo(Object value) {
			addCriterion("rork =", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkNotEqualTo(Object value) {
			addCriterion("rork <>", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkGreaterThan(Object value) {
			addCriterion("rork >", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkGreaterThanOrEqualTo(Object value) {
			addCriterion("rork >=", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkLessThan(Object value) {
			addCriterion("rork <", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkLessThanOrEqualTo(Object value) {
			addCriterion("rork <=", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkIn(List<Object> values) {
			addCriterion("rork in", values, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkNotIn(List<Object> values) {
			addCriterion("rork not in", values, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkBetween(Object value1, Object value2) {
			addCriterion("rork between", value1, value2, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkNotBetween(Object value1, Object value2) {
			addCriterion("rork not between", value1, value2, "rork");
			return (Criteria) this;
		}

		public Criteria andBexpIsNull() {
			addCriterion("bexp is null");
			return (Criteria) this;
		}

		public Criteria andBexpIsNotNull() {
			addCriterion("bexp is not null");
			return (Criteria) this;
		}

		public Criteria andBexpEqualTo(Object value) {
			addCriterion("bexp =", value, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpNotEqualTo(Object value) {
			addCriterion("bexp <>", value, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpGreaterThan(Object value) {
			addCriterion("bexp >", value, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpGreaterThanOrEqualTo(Object value) {
			addCriterion("bexp >=", value, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpLessThan(Object value) {
			addCriterion("bexp <", value, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpLessThanOrEqualTo(Object value) {
			addCriterion("bexp <=", value, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpIn(List<Object> values) {
			addCriterion("bexp in", values, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpNotIn(List<Object> values) {
			addCriterion("bexp not in", values, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpBetween(Object value1, Object value2) {
			addCriterion("bexp between", value1, value2, "bexp");
			return (Criteria) this;
		}

		public Criteria andBexpNotBetween(Object value1, Object value2) {
			addCriterion("bexp not between", value1, value2, "bexp");
			return (Criteria) this;
		}

		public Criteria andRexpIsNull() {
			addCriterion("rexp is null");
			return (Criteria) this;
		}

		public Criteria andRexpIsNotNull() {
			addCriterion("rexp is not null");
			return (Criteria) this;
		}

		public Criteria andRexpEqualTo(Object value) {
			addCriterion("rexp =", value, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpNotEqualTo(Object value) {
			addCriterion("rexp <>", value, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpGreaterThan(Object value) {
			addCriterion("rexp >", value, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpGreaterThanOrEqualTo(Object value) {
			addCriterion("rexp >=", value, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpLessThan(Object value) {
			addCriterion("rexp <", value, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpLessThanOrEqualTo(Object value) {
			addCriterion("rexp <=", value, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpIn(List<Object> values) {
			addCriterion("rexp in", values, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpNotIn(List<Object> values) {
			addCriterion("rexp not in", values, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpBetween(Object value1, Object value2) {
			addCriterion("rexp between", value1, value2, "rexp");
			return (Criteria) this;
		}

		public Criteria andRexpNotBetween(Object value1, Object value2) {
			addCriterion("rexp not between", value1, value2, "rexp");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.ml_expected
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.ml_expected
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}