package com.pengkong.boatrace.mybatis.entity;

public class MlExpectedPlus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.modelno
     *
     * @mbg.generated
     */
    private String modelno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.ymd
     *
     * @mbg.generated
     */
    private String ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.jyocd
     *
     * @mbg.generated
     */
    private String jyocd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.raceno
     *
     * @mbg.generated
     */
    private Short raceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.bkumiban
     *
     * @mbg.generated
     */
    private Object bkumiban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.bprob
     *
     * @mbg.generated
     */
    private Object bprob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.bor
     *
     * @mbg.generated
     */
    private Object bor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.bork
     *
     * @mbg.generated
     */
    private Object bork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.bexp
     *
     * @mbg.generated
     */
    private Object bexp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.bcnt
     *
     * @mbg.generated
     */
    private Integer bcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.rkumiban
     *
     * @mbg.generated
     */
    private Object rkumiban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.rprob
     *
     * @mbg.generated
     */
    private Object rprob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.ror
     *
     * @mbg.generated
     */
    private Object ror;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.rork
     *
     * @mbg.generated
     */
    private Object rork;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.rexp
     *
     * @mbg.generated
     */
    private Object rexp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ml_expected_plus.rcnt
     *
     * @mbg.generated
     */
    private Integer rcnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.modelno
     *
     * @return the value of public.ml_expected_plus.modelno
     *
     * @mbg.generated
     */
    public String getModelno() {
        return modelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.modelno
     *
     * @param modelno the value for public.ml_expected_plus.modelno
     *
     * @mbg.generated
     */
    public void setModelno(String modelno) {
        this.modelno = modelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.ymd
     *
     * @return the value of public.ml_expected_plus.ymd
     *
     * @mbg.generated
     */
    public String getYmd() {
        return ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.ymd
     *
     * @param ymd the value for public.ml_expected_plus.ymd
     *
     * @mbg.generated
     */
    public void setYmd(String ymd) {
        this.ymd = ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.jyocd
     *
     * @return the value of public.ml_expected_plus.jyocd
     *
     * @mbg.generated
     */
    public String getJyocd() {
        return jyocd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.jyocd
     *
     * @param jyocd the value for public.ml_expected_plus.jyocd
     *
     * @mbg.generated
     */
    public void setJyocd(String jyocd) {
        this.jyocd = jyocd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.raceno
     *
     * @return the value of public.ml_expected_plus.raceno
     *
     * @mbg.generated
     */
    public Short getRaceno() {
        return raceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.raceno
     *
     * @param raceno the value for public.ml_expected_plus.raceno
     *
     * @mbg.generated
     */
    public void setRaceno(Short raceno) {
        this.raceno = raceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.bkumiban
     *
     * @return the value of public.ml_expected_plus.bkumiban
     *
     * @mbg.generated
     */
    public Object getBkumiban() {
        return bkumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.bkumiban
     *
     * @param bkumiban the value for public.ml_expected_plus.bkumiban
     *
     * @mbg.generated
     */
    public void setBkumiban(Object bkumiban) {
        this.bkumiban = bkumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.bprob
     *
     * @return the value of public.ml_expected_plus.bprob
     *
     * @mbg.generated
     */
    public Object getBprob() {
        return bprob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.bprob
     *
     * @param bprob the value for public.ml_expected_plus.bprob
     *
     * @mbg.generated
     */
    public void setBprob(Object bprob) {
        this.bprob = bprob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.bor
     *
     * @return the value of public.ml_expected_plus.bor
     *
     * @mbg.generated
     */
    public Object getBor() {
        return bor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.bor
     *
     * @param bor the value for public.ml_expected_plus.bor
     *
     * @mbg.generated
     */
    public void setBor(Object bor) {
        this.bor = bor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.bork
     *
     * @return the value of public.ml_expected_plus.bork
     *
     * @mbg.generated
     */
    public Object getBork() {
        return bork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.bork
     *
     * @param bork the value for public.ml_expected_plus.bork
     *
     * @mbg.generated
     */
    public void setBork(Object bork) {
        this.bork = bork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.bexp
     *
     * @return the value of public.ml_expected_plus.bexp
     *
     * @mbg.generated
     */
    public Object getBexp() {
        return bexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.bexp
     *
     * @param bexp the value for public.ml_expected_plus.bexp
     *
     * @mbg.generated
     */
    public void setBexp(Object bexp) {
        this.bexp = bexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.bcnt
     *
     * @return the value of public.ml_expected_plus.bcnt
     *
     * @mbg.generated
     */
    public Integer getBcnt() {
        return bcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.bcnt
     *
     * @param bcnt the value for public.ml_expected_plus.bcnt
     *
     * @mbg.generated
     */
    public void setBcnt(Integer bcnt) {
        this.bcnt = bcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.rkumiban
     *
     * @return the value of public.ml_expected_plus.rkumiban
     *
     * @mbg.generated
     */
    public Object getRkumiban() {
        return rkumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.rkumiban
     *
     * @param rkumiban the value for public.ml_expected_plus.rkumiban
     *
     * @mbg.generated
     */
    public void setRkumiban(Object rkumiban) {
        this.rkumiban = rkumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.rprob
     *
     * @return the value of public.ml_expected_plus.rprob
     *
     * @mbg.generated
     */
    public Object getRprob() {
        return rprob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.rprob
     *
     * @param rprob the value for public.ml_expected_plus.rprob
     *
     * @mbg.generated
     */
    public void setRprob(Object rprob) {
        this.rprob = rprob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.ror
     *
     * @return the value of public.ml_expected_plus.ror
     *
     * @mbg.generated
     */
    public Object getRor() {
        return ror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.ror
     *
     * @param ror the value for public.ml_expected_plus.ror
     *
     * @mbg.generated
     */
    public void setRor(Object ror) {
        this.ror = ror;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.rork
     *
     * @return the value of public.ml_expected_plus.rork
     *
     * @mbg.generated
     */
    public Object getRork() {
        return rork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.rork
     *
     * @param rork the value for public.ml_expected_plus.rork
     *
     * @mbg.generated
     */
    public void setRork(Object rork) {
        this.rork = rork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.rexp
     *
     * @return the value of public.ml_expected_plus.rexp
     *
     * @mbg.generated
     */
    public Object getRexp() {
        return rexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.rexp
     *
     * @param rexp the value for public.ml_expected_plus.rexp
     *
     * @mbg.generated
     */
    public void setRexp(Object rexp) {
        this.rexp = rexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ml_expected_plus.rcnt
     *
     * @return the value of public.ml_expected_plus.rcnt
     *
     * @mbg.generated
     */
    public Integer getRcnt() {
        return rcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ml_expected_plus.rcnt
     *
     * @param rcnt the value for public.ml_expected_plus.rcnt
     *
     * @mbg.generated
     */
    public void setRcnt(Integer rcnt) {
        this.rcnt = rcnt;
    }
}