package com.pengkong.boatrace.mybatis.entity;

public class MlTermEvaluation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.resultno
	 * @mbg.generated
	 */
	private String resultno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.modelno
	 * @mbg.generated
	 */
	private String modelno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.patternid
	 * @mbg.generated
	 */
	private String patternid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.pattern
	 * @mbg.generated
	 */
	private String pattern;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.bettype
	 * @mbg.generated
	 */
	private String bettype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.kumiban
	 * @mbg.generated
	 */
	private String kumiban;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.termcnt
	 * @mbg.generated
	 */
	private Integer termcnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.pluscnt
	 * @mbg.generated
	 */
	private Integer pluscnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.plusrate
	 * @mbg.generated
	 */
	private Double plusrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.betcnt_min
	 * @mbg.generated
	 */
	private Double betcntMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.betcnt_max
	 * @mbg.generated
	 */
	private Double betcntMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.betcnt_mean
	 * @mbg.generated
	 */
	private Double betcntMean;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.betcnt_stddev
	 * @mbg.generated
	 */
	private Double betcntStddev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.betcnt_median
	 * @mbg.generated
	 */
	private Double betcntMedian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.inc_min
	 * @mbg.generated
	 */
	private Double incMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.inc_max
	 * @mbg.generated
	 */
	private Double incMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.inc_mean
	 * @mbg.generated
	 */
	private Double incMean;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.inc_stddev
	 * @mbg.generated
	 */
	private Double incStddev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.inc_median
	 * @mbg.generated
	 */
	private Double incMedian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.hitr_min
	 * @mbg.generated
	 */
	private Double hitrMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.hitr_max
	 * @mbg.generated
	 */
	private Double hitrMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.hitr_mean
	 * @mbg.generated
	 */
	private Double hitrMean;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.hitr_stddev
	 * @mbg.generated
	 */
	private Double hitrStddev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.hitr_median
	 * @mbg.generated
	 */
	private Double hitrMedian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.incr_min
	 * @mbg.generated
	 */
	private Double incrMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.incr_max
	 * @mbg.generated
	 */
	private Double incrMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.incr_mean
	 * @mbg.generated
	 */
	private Double incrMean;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.incr_stddev
	 * @mbg.generated
	 */
	private Double incrStddev;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.incr_median
	 * @mbg.generated
	 */
	private Double incrMedian;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.result_type
	 * @mbg.generated
	 */
	private String resultType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ml_term_evaluation.evaluations_id
	 * @mbg.generated
	 */
	private String evaluationsId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.resultno
	 * @return  the value of public.ml_term_evaluation.resultno
	 * @mbg.generated
	 */
	public String getResultno() {
		return resultno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.resultno
	 * @param resultno  the value for public.ml_term_evaluation.resultno
	 * @mbg.generated
	 */
	public void setResultno(String resultno) {
		this.resultno = resultno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.modelno
	 * @return  the value of public.ml_term_evaluation.modelno
	 * @mbg.generated
	 */
	public String getModelno() {
		return modelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.modelno
	 * @param modelno  the value for public.ml_term_evaluation.modelno
	 * @mbg.generated
	 */
	public void setModelno(String modelno) {
		this.modelno = modelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.patternid
	 * @return  the value of public.ml_term_evaluation.patternid
	 * @mbg.generated
	 */
	public String getPatternid() {
		return patternid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.patternid
	 * @param patternid  the value for public.ml_term_evaluation.patternid
	 * @mbg.generated
	 */
	public void setPatternid(String patternid) {
		this.patternid = patternid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.pattern
	 * @return  the value of public.ml_term_evaluation.pattern
	 * @mbg.generated
	 */
	public String getPattern() {
		return pattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.pattern
	 * @param pattern  the value for public.ml_term_evaluation.pattern
	 * @mbg.generated
	 */
	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.bettype
	 * @return  the value of public.ml_term_evaluation.bettype
	 * @mbg.generated
	 */
	public String getBettype() {
		return bettype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.bettype
	 * @param bettype  the value for public.ml_term_evaluation.bettype
	 * @mbg.generated
	 */
	public void setBettype(String bettype) {
		this.bettype = bettype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.kumiban
	 * @return  the value of public.ml_term_evaluation.kumiban
	 * @mbg.generated
	 */
	public String getKumiban() {
		return kumiban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.kumiban
	 * @param kumiban  the value for public.ml_term_evaluation.kumiban
	 * @mbg.generated
	 */
	public void setKumiban(String kumiban) {
		this.kumiban = kumiban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.termcnt
	 * @return  the value of public.ml_term_evaluation.termcnt
	 * @mbg.generated
	 */
	public Integer getTermcnt() {
		return termcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.termcnt
	 * @param termcnt  the value for public.ml_term_evaluation.termcnt
	 * @mbg.generated
	 */
	public void setTermcnt(Integer termcnt) {
		this.termcnt = termcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.pluscnt
	 * @return  the value of public.ml_term_evaluation.pluscnt
	 * @mbg.generated
	 */
	public Integer getPluscnt() {
		return pluscnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.pluscnt
	 * @param pluscnt  the value for public.ml_term_evaluation.pluscnt
	 * @mbg.generated
	 */
	public void setPluscnt(Integer pluscnt) {
		this.pluscnt = pluscnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.plusrate
	 * @return  the value of public.ml_term_evaluation.plusrate
	 * @mbg.generated
	 */
	public Double getPlusrate() {
		return plusrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.plusrate
	 * @param plusrate  the value for public.ml_term_evaluation.plusrate
	 * @mbg.generated
	 */
	public void setPlusrate(Double plusrate) {
		this.plusrate = plusrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.betcnt_min
	 * @return  the value of public.ml_term_evaluation.betcnt_min
	 * @mbg.generated
	 */
	public Double getBetcntMin() {
		return betcntMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.betcnt_min
	 * @param betcntMin  the value for public.ml_term_evaluation.betcnt_min
	 * @mbg.generated
	 */
	public void setBetcntMin(Double betcntMin) {
		this.betcntMin = betcntMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.betcnt_max
	 * @return  the value of public.ml_term_evaluation.betcnt_max
	 * @mbg.generated
	 */
	public Double getBetcntMax() {
		return betcntMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.betcnt_max
	 * @param betcntMax  the value for public.ml_term_evaluation.betcnt_max
	 * @mbg.generated
	 */
	public void setBetcntMax(Double betcntMax) {
		this.betcntMax = betcntMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.betcnt_mean
	 * @return  the value of public.ml_term_evaluation.betcnt_mean
	 * @mbg.generated
	 */
	public Double getBetcntMean() {
		return betcntMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.betcnt_mean
	 * @param betcntMean  the value for public.ml_term_evaluation.betcnt_mean
	 * @mbg.generated
	 */
	public void setBetcntMean(Double betcntMean) {
		this.betcntMean = betcntMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.betcnt_stddev
	 * @return  the value of public.ml_term_evaluation.betcnt_stddev
	 * @mbg.generated
	 */
	public Double getBetcntStddev() {
		return betcntStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.betcnt_stddev
	 * @param betcntStddev  the value for public.ml_term_evaluation.betcnt_stddev
	 * @mbg.generated
	 */
	public void setBetcntStddev(Double betcntStddev) {
		this.betcntStddev = betcntStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.betcnt_median
	 * @return  the value of public.ml_term_evaluation.betcnt_median
	 * @mbg.generated
	 */
	public Double getBetcntMedian() {
		return betcntMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.betcnt_median
	 * @param betcntMedian  the value for public.ml_term_evaluation.betcnt_median
	 * @mbg.generated
	 */
	public void setBetcntMedian(Double betcntMedian) {
		this.betcntMedian = betcntMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.inc_min
	 * @return  the value of public.ml_term_evaluation.inc_min
	 * @mbg.generated
	 */
	public Double getIncMin() {
		return incMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.inc_min
	 * @param incMin  the value for public.ml_term_evaluation.inc_min
	 * @mbg.generated
	 */
	public void setIncMin(Double incMin) {
		this.incMin = incMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.inc_max
	 * @return  the value of public.ml_term_evaluation.inc_max
	 * @mbg.generated
	 */
	public Double getIncMax() {
		return incMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.inc_max
	 * @param incMax  the value for public.ml_term_evaluation.inc_max
	 * @mbg.generated
	 */
	public void setIncMax(Double incMax) {
		this.incMax = incMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.inc_mean
	 * @return  the value of public.ml_term_evaluation.inc_mean
	 * @mbg.generated
	 */
	public Double getIncMean() {
		return incMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.inc_mean
	 * @param incMean  the value for public.ml_term_evaluation.inc_mean
	 * @mbg.generated
	 */
	public void setIncMean(Double incMean) {
		this.incMean = incMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.inc_stddev
	 * @return  the value of public.ml_term_evaluation.inc_stddev
	 * @mbg.generated
	 */
	public Double getIncStddev() {
		return incStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.inc_stddev
	 * @param incStddev  the value for public.ml_term_evaluation.inc_stddev
	 * @mbg.generated
	 */
	public void setIncStddev(Double incStddev) {
		this.incStddev = incStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.inc_median
	 * @return  the value of public.ml_term_evaluation.inc_median
	 * @mbg.generated
	 */
	public Double getIncMedian() {
		return incMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.inc_median
	 * @param incMedian  the value for public.ml_term_evaluation.inc_median
	 * @mbg.generated
	 */
	public void setIncMedian(Double incMedian) {
		this.incMedian = incMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.hitr_min
	 * @return  the value of public.ml_term_evaluation.hitr_min
	 * @mbg.generated
	 */
	public Double getHitrMin() {
		return hitrMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.hitr_min
	 * @param hitrMin  the value for public.ml_term_evaluation.hitr_min
	 * @mbg.generated
	 */
	public void setHitrMin(Double hitrMin) {
		this.hitrMin = hitrMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.hitr_max
	 * @return  the value of public.ml_term_evaluation.hitr_max
	 * @mbg.generated
	 */
	public Double getHitrMax() {
		return hitrMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.hitr_max
	 * @param hitrMax  the value for public.ml_term_evaluation.hitr_max
	 * @mbg.generated
	 */
	public void setHitrMax(Double hitrMax) {
		this.hitrMax = hitrMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.hitr_mean
	 * @return  the value of public.ml_term_evaluation.hitr_mean
	 * @mbg.generated
	 */
	public Double getHitrMean() {
		return hitrMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.hitr_mean
	 * @param hitrMean  the value for public.ml_term_evaluation.hitr_mean
	 * @mbg.generated
	 */
	public void setHitrMean(Double hitrMean) {
		this.hitrMean = hitrMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.hitr_stddev
	 * @return  the value of public.ml_term_evaluation.hitr_stddev
	 * @mbg.generated
	 */
	public Double getHitrStddev() {
		return hitrStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.hitr_stddev
	 * @param hitrStddev  the value for public.ml_term_evaluation.hitr_stddev
	 * @mbg.generated
	 */
	public void setHitrStddev(Double hitrStddev) {
		this.hitrStddev = hitrStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.hitr_median
	 * @return  the value of public.ml_term_evaluation.hitr_median
	 * @mbg.generated
	 */
	public Double getHitrMedian() {
		return hitrMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.hitr_median
	 * @param hitrMedian  the value for public.ml_term_evaluation.hitr_median
	 * @mbg.generated
	 */
	public void setHitrMedian(Double hitrMedian) {
		this.hitrMedian = hitrMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.incr_min
	 * @return  the value of public.ml_term_evaluation.incr_min
	 * @mbg.generated
	 */
	public Double getIncrMin() {
		return incrMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.incr_min
	 * @param incrMin  the value for public.ml_term_evaluation.incr_min
	 * @mbg.generated
	 */
	public void setIncrMin(Double incrMin) {
		this.incrMin = incrMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.incr_max
	 * @return  the value of public.ml_term_evaluation.incr_max
	 * @mbg.generated
	 */
	public Double getIncrMax() {
		return incrMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.incr_max
	 * @param incrMax  the value for public.ml_term_evaluation.incr_max
	 * @mbg.generated
	 */
	public void setIncrMax(Double incrMax) {
		this.incrMax = incrMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.incr_mean
	 * @return  the value of public.ml_term_evaluation.incr_mean
	 * @mbg.generated
	 */
	public Double getIncrMean() {
		return incrMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.incr_mean
	 * @param incrMean  the value for public.ml_term_evaluation.incr_mean
	 * @mbg.generated
	 */
	public void setIncrMean(Double incrMean) {
		this.incrMean = incrMean;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.incr_stddev
	 * @return  the value of public.ml_term_evaluation.incr_stddev
	 * @mbg.generated
	 */
	public Double getIncrStddev() {
		return incrStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.incr_stddev
	 * @param incrStddev  the value for public.ml_term_evaluation.incr_stddev
	 * @mbg.generated
	 */
	public void setIncrStddev(Double incrStddev) {
		this.incrStddev = incrStddev;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.incr_median
	 * @return  the value of public.ml_term_evaluation.incr_median
	 * @mbg.generated
	 */
	public Double getIncrMedian() {
		return incrMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.incr_median
	 * @param incrMedian  the value for public.ml_term_evaluation.incr_median
	 * @mbg.generated
	 */
	public void setIncrMedian(Double incrMedian) {
		this.incrMedian = incrMedian;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.result_type
	 * @return  the value of public.ml_term_evaluation.result_type
	 * @mbg.generated
	 */
	public String getResultType() {
		return resultType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.result_type
	 * @param resultType  the value for public.ml_term_evaluation.result_type
	 * @mbg.generated
	 */
	public void setResultType(String resultType) {
		this.resultType = resultType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ml_term_evaluation.evaluations_id
	 * @return  the value of public.ml_term_evaluation.evaluations_id
	 * @mbg.generated
	 */
	public String getEvaluationsId() {
		return evaluationsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ml_term_evaluation.evaluations_id
	 * @param evaluationsId  the value for public.ml_term_evaluation.evaluations_id
	 * @mbg.generated
	 */
	public void setEvaluationsId(String evaluationsId) {
		this.evaluationsId = evaluationsId;
	}
}