package com.pengkong.boatrace.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class OddsMonitorExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public OddsMonitorExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andYmdIsNull() {
			addCriterion("ymd is null");
			return (Criteria) this;
		}

		public Criteria andYmdIsNotNull() {
			addCriterion("ymd is not null");
			return (Criteria) this;
		}

		public Criteria andYmdEqualTo(String value) {
			addCriterion("ymd =", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotEqualTo(String value) {
			addCriterion("ymd <>", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdGreaterThan(String value) {
			addCriterion("ymd >", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdGreaterThanOrEqualTo(String value) {
			addCriterion("ymd >=", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLessThan(String value) {
			addCriterion("ymd <", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLessThanOrEqualTo(String value) {
			addCriterion("ymd <=", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLike(String value) {
			addCriterion("ymd like", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotLike(String value) {
			addCriterion("ymd not like", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdIn(List<String> values) {
			addCriterion("ymd in", values, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotIn(List<String> values) {
			addCriterion("ymd not in", values, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdBetween(String value1, String value2) {
			addCriterion("ymd between", value1, value2, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotBetween(String value1, String value2) {
			addCriterion("ymd not between", value1, value2, "ymd");
			return (Criteria) this;
		}

		public Criteria andJyocdIsNull() {
			addCriterion("jyocd is null");
			return (Criteria) this;
		}

		public Criteria andJyocdIsNotNull() {
			addCriterion("jyocd is not null");
			return (Criteria) this;
		}

		public Criteria andJyocdEqualTo(String value) {
			addCriterion("jyocd =", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotEqualTo(String value) {
			addCriterion("jyocd <>", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdGreaterThan(String value) {
			addCriterion("jyocd >", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdGreaterThanOrEqualTo(String value) {
			addCriterion("jyocd >=", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLessThan(String value) {
			addCriterion("jyocd <", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLessThanOrEqualTo(String value) {
			addCriterion("jyocd <=", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLike(String value) {
			addCriterion("jyocd like", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotLike(String value) {
			addCriterion("jyocd not like", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdIn(List<String> values) {
			addCriterion("jyocd in", values, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotIn(List<String> values) {
			addCriterion("jyocd not in", values, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdBetween(String value1, String value2) {
			addCriterion("jyocd between", value1, value2, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotBetween(String value1, String value2) {
			addCriterion("jyocd not between", value1, value2, "jyocd");
			return (Criteria) this;
		}

		public Criteria andRacenoIsNull() {
			addCriterion("raceno is null");
			return (Criteria) this;
		}

		public Criteria andRacenoIsNotNull() {
			addCriterion("raceno is not null");
			return (Criteria) this;
		}

		public Criteria andRacenoEqualTo(Short value) {
			addCriterion("raceno =", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotEqualTo(Short value) {
			addCriterion("raceno <>", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoGreaterThan(Short value) {
			addCriterion("raceno >", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoGreaterThanOrEqualTo(Short value) {
			addCriterion("raceno >=", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoLessThan(Short value) {
			addCriterion("raceno <", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoLessThanOrEqualTo(Short value) {
			addCriterion("raceno <=", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoIn(List<Short> values) {
			addCriterion("raceno in", values, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotIn(List<Short> values) {
			addCriterion("raceno not in", values, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoBetween(Short value1, Short value2) {
			addCriterion("raceno between", value1, value2, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotBetween(Short value1, Short value2) {
			addCriterion("raceno not between", value1, value2, "raceno");
			return (Criteria) this;
		}

		public Criteria andBettypeIsNull() {
			addCriterion("bettype is null");
			return (Criteria) this;
		}

		public Criteria andBettypeIsNotNull() {
			addCriterion("bettype is not null");
			return (Criteria) this;
		}

		public Criteria andBettypeEqualTo(String value) {
			addCriterion("bettype =", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotEqualTo(String value) {
			addCriterion("bettype <>", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeGreaterThan(String value) {
			addCriterion("bettype >", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeGreaterThanOrEqualTo(String value) {
			addCriterion("bettype >=", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeLessThan(String value) {
			addCriterion("bettype <", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeLessThanOrEqualTo(String value) {
			addCriterion("bettype <=", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeLike(String value) {
			addCriterion("bettype like", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotLike(String value) {
			addCriterion("bettype not like", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeIn(List<String> values) {
			addCriterion("bettype in", values, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotIn(List<String> values) {
			addCriterion("bettype not in", values, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeBetween(String value1, String value2) {
			addCriterion("bettype between", value1, value2, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotBetween(String value1, String value2) {
			addCriterion("bettype not between", value1, value2, "bettype");
			return (Criteria) this;
		}

		public Criteria andKumibanIsNull() {
			addCriterion("kumiban is null");
			return (Criteria) this;
		}

		public Criteria andKumibanIsNotNull() {
			addCriterion("kumiban is not null");
			return (Criteria) this;
		}

		public Criteria andKumibanEqualTo(String value) {
			addCriterion("kumiban =", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanNotEqualTo(String value) {
			addCriterion("kumiban <>", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanGreaterThan(String value) {
			addCriterion("kumiban >", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanGreaterThanOrEqualTo(String value) {
			addCriterion("kumiban >=", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanLessThan(String value) {
			addCriterion("kumiban <", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanLessThanOrEqualTo(String value) {
			addCriterion("kumiban <=", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanLike(String value) {
			addCriterion("kumiban like", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanNotLike(String value) {
			addCriterion("kumiban not like", value, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanIn(List<String> values) {
			addCriterion("kumiban in", values, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanNotIn(List<String> values) {
			addCriterion("kumiban not in", values, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanBetween(String value1, String value2) {
			addCriterion("kumiban between", value1, value2, "kumiban");
			return (Criteria) this;
		}

		public Criteria andKumibanNotBetween(String value1, String value2) {
			addCriterion("kumiban not between", value1, value2, "kumiban");
			return (Criteria) this;
		}

		public Criteria andBorkIsNull() {
			addCriterion("bork is null");
			return (Criteria) this;
		}

		public Criteria andBorkIsNotNull() {
			addCriterion("bork is not null");
			return (Criteria) this;
		}

		public Criteria andBorkEqualTo(Integer value) {
			addCriterion("bork =", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkNotEqualTo(Integer value) {
			addCriterion("bork <>", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkGreaterThan(Integer value) {
			addCriterion("bork >", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkGreaterThanOrEqualTo(Integer value) {
			addCriterion("bork >=", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkLessThan(Integer value) {
			addCriterion("bork <", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkLessThanOrEqualTo(Integer value) {
			addCriterion("bork <=", value, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkIn(List<Integer> values) {
			addCriterion("bork in", values, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkNotIn(List<Integer> values) {
			addCriterion("bork not in", values, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkBetween(Integer value1, Integer value2) {
			addCriterion("bork between", value1, value2, "bork");
			return (Criteria) this;
		}

		public Criteria andBorkNotBetween(Integer value1, Integer value2) {
			addCriterion("bork not between", value1, value2, "bork");
			return (Criteria) this;
		}

		public Criteria andBorIsNull() {
			addCriterion("bor is null");
			return (Criteria) this;
		}

		public Criteria andBorIsNotNull() {
			addCriterion("bor is not null");
			return (Criteria) this;
		}

		public Criteria andBorEqualTo(Double value) {
			addCriterion("bor =", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorNotEqualTo(Double value) {
			addCriterion("bor <>", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorGreaterThan(Double value) {
			addCriterion("bor >", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorGreaterThanOrEqualTo(Double value) {
			addCriterion("bor >=", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorLessThan(Double value) {
			addCriterion("bor <", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorLessThanOrEqualTo(Double value) {
			addCriterion("bor <=", value, "bor");
			return (Criteria) this;
		}

		public Criteria andBorIn(List<Double> values) {
			addCriterion("bor in", values, "bor");
			return (Criteria) this;
		}

		public Criteria andBorNotIn(List<Double> values) {
			addCriterion("bor not in", values, "bor");
			return (Criteria) this;
		}

		public Criteria andBorBetween(Double value1, Double value2) {
			addCriterion("bor between", value1, value2, "bor");
			return (Criteria) this;
		}

		public Criteria andBorNotBetween(Double value1, Double value2) {
			addCriterion("bor not between", value1, value2, "bor");
			return (Criteria) this;
		}

		public Criteria andRorkIsNull() {
			addCriterion("rork is null");
			return (Criteria) this;
		}

		public Criteria andRorkIsNotNull() {
			addCriterion("rork is not null");
			return (Criteria) this;
		}

		public Criteria andRorkEqualTo(Integer value) {
			addCriterion("rork =", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkNotEqualTo(Integer value) {
			addCriterion("rork <>", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkGreaterThan(Integer value) {
			addCriterion("rork >", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkGreaterThanOrEqualTo(Integer value) {
			addCriterion("rork >=", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkLessThan(Integer value) {
			addCriterion("rork <", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkLessThanOrEqualTo(Integer value) {
			addCriterion("rork <=", value, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkIn(List<Integer> values) {
			addCriterion("rork in", values, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkNotIn(List<Integer> values) {
			addCriterion("rork not in", values, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkBetween(Integer value1, Integer value2) {
			addCriterion("rork between", value1, value2, "rork");
			return (Criteria) this;
		}

		public Criteria andRorkNotBetween(Integer value1, Integer value2) {
			addCriterion("rork not between", value1, value2, "rork");
			return (Criteria) this;
		}

		public Criteria andRorIsNull() {
			addCriterion("ror is null");
			return (Criteria) this;
		}

		public Criteria andRorIsNotNull() {
			addCriterion("ror is not null");
			return (Criteria) this;
		}

		public Criteria andRorEqualTo(Double value) {
			addCriterion("ror =", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorNotEqualTo(Double value) {
			addCriterion("ror <>", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorGreaterThan(Double value) {
			addCriterion("ror >", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorGreaterThanOrEqualTo(Double value) {
			addCriterion("ror >=", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorLessThan(Double value) {
			addCriterion("ror <", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorLessThanOrEqualTo(Double value) {
			addCriterion("ror <=", value, "ror");
			return (Criteria) this;
		}

		public Criteria andRorIn(List<Double> values) {
			addCriterion("ror in", values, "ror");
			return (Criteria) this;
		}

		public Criteria andRorNotIn(List<Double> values) {
			addCriterion("ror not in", values, "ror");
			return (Criteria) this;
		}

		public Criteria andRorBetween(Double value1, Double value2) {
			addCriterion("ror between", value1, value2, "ror");
			return (Criteria) this;
		}

		public Criteria andRorNotBetween(Double value1, Double value2) {
			addCriterion("ror not between", value1, value2, "ror");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.odds_monitor
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}