package com.pengkong.boatrace.mybatis.entity;

public class OlClassification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.modelno
     *
     * @mbg.generated
     */
    private String modelno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.ymd
     *
     * @mbg.generated
     */
    private String ymd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.jyocd
     *
     * @mbg.generated
     */
    private String jyocd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.raceno
     *
     * @mbg.generated
     */
    private Integer raceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.sime
     *
     * @mbg.generated
     */
    private String sime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.prediction1
     *
     * @mbg.generated
     */
    private String prediction1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.probability1
     *
     * @mbg.generated
     */
    private Double probability1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.probabilities1
     *
     * @mbg.generated
     */
    private Object probabilities1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.prediction2
     *
     * @mbg.generated
     */
    private String prediction2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.probability2
     *
     * @mbg.generated
     */
    private Double probability2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.probabilities2
     *
     * @mbg.generated
     */
    private Object probabilities2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.prediction3
     *
     * @mbg.generated
     */
    private String prediction3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.probability3
     *
     * @mbg.generated
     */
    private Double probability3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ol_classification.probabilities3
     *
     * @mbg.generated
     */
    private Object probabilities3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.modelno
     *
     * @return the value of public.ol_classification.modelno
     *
     * @mbg.generated
     */
    public String getModelno() {
        return modelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.modelno
     *
     * @param modelno the value for public.ol_classification.modelno
     *
     * @mbg.generated
     */
    public void setModelno(String modelno) {
        this.modelno = modelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.ymd
     *
     * @return the value of public.ol_classification.ymd
     *
     * @mbg.generated
     */
    public String getYmd() {
        return ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.ymd
     *
     * @param ymd the value for public.ol_classification.ymd
     *
     * @mbg.generated
     */
    public void setYmd(String ymd) {
        this.ymd = ymd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.jyocd
     *
     * @return the value of public.ol_classification.jyocd
     *
     * @mbg.generated
     */
    public String getJyocd() {
        return jyocd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.jyocd
     *
     * @param jyocd the value for public.ol_classification.jyocd
     *
     * @mbg.generated
     */
    public void setJyocd(String jyocd) {
        this.jyocd = jyocd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.raceno
     *
     * @return the value of public.ol_classification.raceno
     *
     * @mbg.generated
     */
    public Integer getRaceno() {
        return raceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.raceno
     *
     * @param raceno the value for public.ol_classification.raceno
     *
     * @mbg.generated
     */
    public void setRaceno(Integer raceno) {
        this.raceno = raceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.sime
     *
     * @return the value of public.ol_classification.sime
     *
     * @mbg.generated
     */
    public String getSime() {
        return sime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.sime
     *
     * @param sime the value for public.ol_classification.sime
     *
     * @mbg.generated
     */
    public void setSime(String sime) {
        this.sime = sime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.prediction1
     *
     * @return the value of public.ol_classification.prediction1
     *
     * @mbg.generated
     */
    public String getPrediction1() {
        return prediction1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.prediction1
     *
     * @param prediction1 the value for public.ol_classification.prediction1
     *
     * @mbg.generated
     */
    public void setPrediction1(String prediction1) {
        this.prediction1 = prediction1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.probability1
     *
     * @return the value of public.ol_classification.probability1
     *
     * @mbg.generated
     */
    public Double getProbability1() {
        return probability1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.probability1
     *
     * @param probability1 the value for public.ol_classification.probability1
     *
     * @mbg.generated
     */
    public void setProbability1(Double probability1) {
        this.probability1 = probability1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.probabilities1
     *
     * @return the value of public.ol_classification.probabilities1
     *
     * @mbg.generated
     */
    public Object getProbabilities1() {
        return probabilities1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.probabilities1
     *
     * @param probabilities1 the value for public.ol_classification.probabilities1
     *
     * @mbg.generated
     */
    public void setProbabilities1(Object probabilities1) {
        this.probabilities1 = probabilities1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.prediction2
     *
     * @return the value of public.ol_classification.prediction2
     *
     * @mbg.generated
     */
    public String getPrediction2() {
        return prediction2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.prediction2
     *
     * @param prediction2 the value for public.ol_classification.prediction2
     *
     * @mbg.generated
     */
    public void setPrediction2(String prediction2) {
        this.prediction2 = prediction2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.probability2
     *
     * @return the value of public.ol_classification.probability2
     *
     * @mbg.generated
     */
    public Double getProbability2() {
        return probability2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.probability2
     *
     * @param probability2 the value for public.ol_classification.probability2
     *
     * @mbg.generated
     */
    public void setProbability2(Double probability2) {
        this.probability2 = probability2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.probabilities2
     *
     * @return the value of public.ol_classification.probabilities2
     *
     * @mbg.generated
     */
    public Object getProbabilities2() {
        return probabilities2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.probabilities2
     *
     * @param probabilities2 the value for public.ol_classification.probabilities2
     *
     * @mbg.generated
     */
    public void setProbabilities2(Object probabilities2) {
        this.probabilities2 = probabilities2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.prediction3
     *
     * @return the value of public.ol_classification.prediction3
     *
     * @mbg.generated
     */
    public String getPrediction3() {
        return prediction3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.prediction3
     *
     * @param prediction3 the value for public.ol_classification.prediction3
     *
     * @mbg.generated
     */
    public void setPrediction3(String prediction3) {
        this.prediction3 = prediction3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.probability3
     *
     * @return the value of public.ol_classification.probability3
     *
     * @mbg.generated
     */
    public Double getProbability3() {
        return probability3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.probability3
     *
     * @param probability3 the value for public.ol_classification.probability3
     *
     * @mbg.generated
     */
    public void setProbability3(Double probability3) {
        this.probability3 = probability3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ol_classification.probabilities3
     *
     * @return the value of public.ol_classification.probabilities3
     *
     * @mbg.generated
     */
    public Object getProbabilities3() {
        return probabilities3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ol_classification.probabilities3
     *
     * @param probabilities3 the value for public.ol_classification.probabilities3
     *
     * @mbg.generated
     */
    public void setProbabilities3(Object probabilities3) {
        this.probabilities3 = probabilities3;
    }
}