package com.pengkong.boatrace.mybatis.entity;

public class OlRacer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.ymd
	 * @mbg.generated
	 */
	private String ymd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.jyocd
	 * @mbg.generated
	 */
	private String jyocd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.raceno
	 * @mbg.generated
	 */
	private Integer raceno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.entry
	 * @mbg.generated
	 */
	private Integer entry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.sex
	 * @mbg.generated
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.age
	 * @mbg.generated
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.level
	 * @mbg.generated
	 */
	private String level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.weight
	 * @mbg.generated
	 */
	private Double weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.branch
	 * @mbg.generated
	 */
	private String branch;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.exhibit
	 * @mbg.generated
	 */
	private Double exhibit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.startexhibit
	 * @mbg.generated
	 */
	private Double startexhibit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.flying
	 * @mbg.generated
	 */
	private Integer flying;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.late
	 * @mbg.generated
	 */
	private Integer late;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.averagestart
	 * @mbg.generated
	 */
	private Double averagestart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.avgtime
	 * @mbg.generated
	 */
	private Double avgtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.nationwiningrate
	 * @mbg.generated
	 */
	private Double nationwiningrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.nation2winingrate
	 * @mbg.generated
	 */
	private Double nation2winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.nation3winingrate
	 * @mbg.generated
	 */
	private Double nation3winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.localwiningrate
	 * @mbg.generated
	 */
	private Double localwiningrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.local2winingrate
	 * @mbg.generated
	 */
	private Double local2winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.local3winingrate
	 * @mbg.generated
	 */
	private Double local3winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.motorno
	 * @mbg.generated
	 */
	private Integer motorno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.motor2winingrate
	 * @mbg.generated
	 */
	private Double motor2winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.motor3winingrate
	 * @mbg.generated
	 */
	private Double motor3winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.boatno
	 * @mbg.generated
	 */
	private Integer boatno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.boat2winingrate
	 * @mbg.generated
	 */
	private Double boat2winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.boat3winingrate
	 * @mbg.generated
	 */
	private Double boat3winingrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.waku
	 * @mbg.generated
	 */
	private Integer waku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.grade
	 * @mbg.generated
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.ol_racer.racetype
	 * @mbg.generated
	 */
	private String racetype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.ymd
	 * @return  the value of public.ol_racer.ymd
	 * @mbg.generated
	 */
	public String getYmd() {
		return ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.ymd
	 * @param ymd  the value for public.ol_racer.ymd
	 * @mbg.generated
	 */
	public void setYmd(String ymd) {
		this.ymd = ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.jyocd
	 * @return  the value of public.ol_racer.jyocd
	 * @mbg.generated
	 */
	public String getJyocd() {
		return jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.jyocd
	 * @param jyocd  the value for public.ol_racer.jyocd
	 * @mbg.generated
	 */
	public void setJyocd(String jyocd) {
		this.jyocd = jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.raceno
	 * @return  the value of public.ol_racer.raceno
	 * @mbg.generated
	 */
	public Integer getRaceno() {
		return raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.raceno
	 * @param raceno  the value for public.ol_racer.raceno
	 * @mbg.generated
	 */
	public void setRaceno(Integer raceno) {
		this.raceno = raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.entry
	 * @return  the value of public.ol_racer.entry
	 * @mbg.generated
	 */
	public Integer getEntry() {
		return entry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.entry
	 * @param entry  the value for public.ol_racer.entry
	 * @mbg.generated
	 */
	public void setEntry(Integer entry) {
		this.entry = entry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.sex
	 * @return  the value of public.ol_racer.sex
	 * @mbg.generated
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.sex
	 * @param sex  the value for public.ol_racer.sex
	 * @mbg.generated
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.age
	 * @return  the value of public.ol_racer.age
	 * @mbg.generated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.age
	 * @param age  the value for public.ol_racer.age
	 * @mbg.generated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.level
	 * @return  the value of public.ol_racer.level
	 * @mbg.generated
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.level
	 * @param level  the value for public.ol_racer.level
	 * @mbg.generated
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.weight
	 * @return  the value of public.ol_racer.weight
	 * @mbg.generated
	 */
	public Double getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.weight
	 * @param weight  the value for public.ol_racer.weight
	 * @mbg.generated
	 */
	public void setWeight(Double weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.branch
	 * @return  the value of public.ol_racer.branch
	 * @mbg.generated
	 */
	public String getBranch() {
		return branch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.branch
	 * @param branch  the value for public.ol_racer.branch
	 * @mbg.generated
	 */
	public void setBranch(String branch) {
		this.branch = branch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.exhibit
	 * @return  the value of public.ol_racer.exhibit
	 * @mbg.generated
	 */
	public Double getExhibit() {
		return exhibit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.exhibit
	 * @param exhibit  the value for public.ol_racer.exhibit
	 * @mbg.generated
	 */
	public void setExhibit(Double exhibit) {
		this.exhibit = exhibit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.startexhibit
	 * @return  the value of public.ol_racer.startexhibit
	 * @mbg.generated
	 */
	public Double getStartexhibit() {
		return startexhibit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.startexhibit
	 * @param startexhibit  the value for public.ol_racer.startexhibit
	 * @mbg.generated
	 */
	public void setStartexhibit(Double startexhibit) {
		this.startexhibit = startexhibit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.flying
	 * @return  the value of public.ol_racer.flying
	 * @mbg.generated
	 */
	public Integer getFlying() {
		return flying;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.flying
	 * @param flying  the value for public.ol_racer.flying
	 * @mbg.generated
	 */
	public void setFlying(Integer flying) {
		this.flying = flying;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.late
	 * @return  the value of public.ol_racer.late
	 * @mbg.generated
	 */
	public Integer getLate() {
		return late;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.late
	 * @param late  the value for public.ol_racer.late
	 * @mbg.generated
	 */
	public void setLate(Integer late) {
		this.late = late;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.averagestart
	 * @return  the value of public.ol_racer.averagestart
	 * @mbg.generated
	 */
	public Double getAveragestart() {
		return averagestart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.averagestart
	 * @param averagestart  the value for public.ol_racer.averagestart
	 * @mbg.generated
	 */
	public void setAveragestart(Double averagestart) {
		this.averagestart = averagestart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.avgtime
	 * @return  the value of public.ol_racer.avgtime
	 * @mbg.generated
	 */
	public Double getAvgtime() {
		return avgtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.avgtime
	 * @param avgtime  the value for public.ol_racer.avgtime
	 * @mbg.generated
	 */
	public void setAvgtime(Double avgtime) {
		this.avgtime = avgtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.nationwiningrate
	 * @return  the value of public.ol_racer.nationwiningrate
	 * @mbg.generated
	 */
	public Double getNationwiningrate() {
		return nationwiningrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.nationwiningrate
	 * @param nationwiningrate  the value for public.ol_racer.nationwiningrate
	 * @mbg.generated
	 */
	public void setNationwiningrate(Double nationwiningrate) {
		this.nationwiningrate = nationwiningrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.nation2winingrate
	 * @return  the value of public.ol_racer.nation2winingrate
	 * @mbg.generated
	 */
	public Double getNation2winingrate() {
		return nation2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.nation2winingrate
	 * @param nation2winingrate  the value for public.ol_racer.nation2winingrate
	 * @mbg.generated
	 */
	public void setNation2winingrate(Double nation2winingrate) {
		this.nation2winingrate = nation2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.nation3winingrate
	 * @return  the value of public.ol_racer.nation3winingrate
	 * @mbg.generated
	 */
	public Double getNation3winingrate() {
		return nation3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.nation3winingrate
	 * @param nation3winingrate  the value for public.ol_racer.nation3winingrate
	 * @mbg.generated
	 */
	public void setNation3winingrate(Double nation3winingrate) {
		this.nation3winingrate = nation3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.localwiningrate
	 * @return  the value of public.ol_racer.localwiningrate
	 * @mbg.generated
	 */
	public Double getLocalwiningrate() {
		return localwiningrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.localwiningrate
	 * @param localwiningrate  the value for public.ol_racer.localwiningrate
	 * @mbg.generated
	 */
	public void setLocalwiningrate(Double localwiningrate) {
		this.localwiningrate = localwiningrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.local2winingrate
	 * @return  the value of public.ol_racer.local2winingrate
	 * @mbg.generated
	 */
	public Double getLocal2winingrate() {
		return local2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.local2winingrate
	 * @param local2winingrate  the value for public.ol_racer.local2winingrate
	 * @mbg.generated
	 */
	public void setLocal2winingrate(Double local2winingrate) {
		this.local2winingrate = local2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.local3winingrate
	 * @return  the value of public.ol_racer.local3winingrate
	 * @mbg.generated
	 */
	public Double getLocal3winingrate() {
		return local3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.local3winingrate
	 * @param local3winingrate  the value for public.ol_racer.local3winingrate
	 * @mbg.generated
	 */
	public void setLocal3winingrate(Double local3winingrate) {
		this.local3winingrate = local3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.motorno
	 * @return  the value of public.ol_racer.motorno
	 * @mbg.generated
	 */
	public Integer getMotorno() {
		return motorno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.motorno
	 * @param motorno  the value for public.ol_racer.motorno
	 * @mbg.generated
	 */
	public void setMotorno(Integer motorno) {
		this.motorno = motorno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.motor2winingrate
	 * @return  the value of public.ol_racer.motor2winingrate
	 * @mbg.generated
	 */
	public Double getMotor2winingrate() {
		return motor2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.motor2winingrate
	 * @param motor2winingrate  the value for public.ol_racer.motor2winingrate
	 * @mbg.generated
	 */
	public void setMotor2winingrate(Double motor2winingrate) {
		this.motor2winingrate = motor2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.motor3winingrate
	 * @return  the value of public.ol_racer.motor3winingrate
	 * @mbg.generated
	 */
	public Double getMotor3winingrate() {
		return motor3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.motor3winingrate
	 * @param motor3winingrate  the value for public.ol_racer.motor3winingrate
	 * @mbg.generated
	 */
	public void setMotor3winingrate(Double motor3winingrate) {
		this.motor3winingrate = motor3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.boatno
	 * @return  the value of public.ol_racer.boatno
	 * @mbg.generated
	 */
	public Integer getBoatno() {
		return boatno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.boatno
	 * @param boatno  the value for public.ol_racer.boatno
	 * @mbg.generated
	 */
	public void setBoatno(Integer boatno) {
		this.boatno = boatno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.boat2winingrate
	 * @return  the value of public.ol_racer.boat2winingrate
	 * @mbg.generated
	 */
	public Double getBoat2winingrate() {
		return boat2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.boat2winingrate
	 * @param boat2winingrate  the value for public.ol_racer.boat2winingrate
	 * @mbg.generated
	 */
	public void setBoat2winingrate(Double boat2winingrate) {
		this.boat2winingrate = boat2winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.boat3winingrate
	 * @return  the value of public.ol_racer.boat3winingrate
	 * @mbg.generated
	 */
	public Double getBoat3winingrate() {
		return boat3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.boat3winingrate
	 * @param boat3winingrate  the value for public.ol_racer.boat3winingrate
	 * @mbg.generated
	 */
	public void setBoat3winingrate(Double boat3winingrate) {
		this.boat3winingrate = boat3winingrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.waku
	 * @return  the value of public.ol_racer.waku
	 * @mbg.generated
	 */
	public Integer getWaku() {
		return waku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.waku
	 * @param waku  the value for public.ol_racer.waku
	 * @mbg.generated
	 */
	public void setWaku(Integer waku) {
		this.waku = waku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.grade
	 * @return  the value of public.ol_racer.grade
	 * @mbg.generated
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.grade
	 * @param grade  the value for public.ol_racer.grade
	 * @mbg.generated
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.ol_racer.racetype
	 * @return  the value of public.ol_racer.racetype
	 * @mbg.generated
	 */
	public String getRacetype() {
		return racetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.ol_racer.racetype
	 * @param racetype  the value for public.ol_racer.racetype
	 * @mbg.generated
	 */
	public void setRacetype(String racetype) {
		this.racetype = racetype;
	}
}