package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;

public class RankExtBalance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.bettype
     *
     * @mbg.generated
     */
    private String bettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.bet_kumiban
     *
     * @mbg.generated
     */
    private String betKumiban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.pattern
     *
     * @mbg.generated
     */
    private String pattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.ranktype
     *
     * @mbg.generated
     */
    private String ranktype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.waku
     *
     * @mbg.generated
     */
    private String waku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.ym
     *
     * @mbg.generated
     */
    private String ym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.betcnt
     *
     * @mbg.generated
     */
    private Integer betcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.hitcnt
     *
     * @mbg.generated
     */
    private Integer hitcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.betamt
     *
     * @mbg.generated
     */
    private Integer betamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.hitamt
     *
     * @mbg.generated
     */
    private Integer hitamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.incomeamt
     *
     * @mbg.generated
     */
    private Integer incomeamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.hitrate
     *
     * @mbg.generated
     */
    private BigDecimal hitrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.incomerate
     *
     * @mbg.generated
     */
    private BigDecimal incomerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.avg_incomeamt
     *
     * @mbg.generated
     */
    private Integer avgIncomeamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.extkey
     *
     * @mbg.generated
     */
    private String extkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.rank_ext_balance.balance
     *
     * @mbg.generated
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.description
     *
     * @return the value of public.rank_ext_balance.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.description
     *
     * @param description the value for public.rank_ext_balance.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.bettype
     *
     * @return the value of public.rank_ext_balance.bettype
     *
     * @mbg.generated
     */
    public String getBettype() {
        return bettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.bettype
     *
     * @param bettype the value for public.rank_ext_balance.bettype
     *
     * @mbg.generated
     */
    public void setBettype(String bettype) {
        this.bettype = bettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.bet_kumiban
     *
     * @return the value of public.rank_ext_balance.bet_kumiban
     *
     * @mbg.generated
     */
    public String getBetKumiban() {
        return betKumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.bet_kumiban
     *
     * @param betKumiban the value for public.rank_ext_balance.bet_kumiban
     *
     * @mbg.generated
     */
    public void setBetKumiban(String betKumiban) {
        this.betKumiban = betKumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.pattern
     *
     * @return the value of public.rank_ext_balance.pattern
     *
     * @mbg.generated
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.pattern
     *
     * @param pattern the value for public.rank_ext_balance.pattern
     *
     * @mbg.generated
     */
    public void setPattern(String pattern) {
        this.pattern = pattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.ranktype
     *
     * @return the value of public.rank_ext_balance.ranktype
     *
     * @mbg.generated
     */
    public String getRanktype() {
        return ranktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.ranktype
     *
     * @param ranktype the value for public.rank_ext_balance.ranktype
     *
     * @mbg.generated
     */
    public void setRanktype(String ranktype) {
        this.ranktype = ranktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.waku
     *
     * @return the value of public.rank_ext_balance.waku
     *
     * @mbg.generated
     */
    public String getWaku() {
        return waku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.waku
     *
     * @param waku the value for public.rank_ext_balance.waku
     *
     * @mbg.generated
     */
    public void setWaku(String waku) {
        this.waku = waku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.ym
     *
     * @return the value of public.rank_ext_balance.ym
     *
     * @mbg.generated
     */
    public String getYm() {
        return ym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.ym
     *
     * @param ym the value for public.rank_ext_balance.ym
     *
     * @mbg.generated
     */
    public void setYm(String ym) {
        this.ym = ym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.betcnt
     *
     * @return the value of public.rank_ext_balance.betcnt
     *
     * @mbg.generated
     */
    public Integer getBetcnt() {
        return betcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.betcnt
     *
     * @param betcnt the value for public.rank_ext_balance.betcnt
     *
     * @mbg.generated
     */
    public void setBetcnt(Integer betcnt) {
        this.betcnt = betcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.hitcnt
     *
     * @return the value of public.rank_ext_balance.hitcnt
     *
     * @mbg.generated
     */
    public Integer getHitcnt() {
        return hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.hitcnt
     *
     * @param hitcnt the value for public.rank_ext_balance.hitcnt
     *
     * @mbg.generated
     */
    public void setHitcnt(Integer hitcnt) {
        this.hitcnt = hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.betamt
     *
     * @return the value of public.rank_ext_balance.betamt
     *
     * @mbg.generated
     */
    public Integer getBetamt() {
        return betamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.betamt
     *
     * @param betamt the value for public.rank_ext_balance.betamt
     *
     * @mbg.generated
     */
    public void setBetamt(Integer betamt) {
        this.betamt = betamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.hitamt
     *
     * @return the value of public.rank_ext_balance.hitamt
     *
     * @mbg.generated
     */
    public Integer getHitamt() {
        return hitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.hitamt
     *
     * @param hitamt the value for public.rank_ext_balance.hitamt
     *
     * @mbg.generated
     */
    public void setHitamt(Integer hitamt) {
        this.hitamt = hitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.incomeamt
     *
     * @return the value of public.rank_ext_balance.incomeamt
     *
     * @mbg.generated
     */
    public Integer getIncomeamt() {
        return incomeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.incomeamt
     *
     * @param incomeamt the value for public.rank_ext_balance.incomeamt
     *
     * @mbg.generated
     */
    public void setIncomeamt(Integer incomeamt) {
        this.incomeamt = incomeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.hitrate
     *
     * @return the value of public.rank_ext_balance.hitrate
     *
     * @mbg.generated
     */
    public BigDecimal getHitrate() {
        return hitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.hitrate
     *
     * @param hitrate the value for public.rank_ext_balance.hitrate
     *
     * @mbg.generated
     */
    public void setHitrate(BigDecimal hitrate) {
        this.hitrate = hitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.incomerate
     *
     * @return the value of public.rank_ext_balance.incomerate
     *
     * @mbg.generated
     */
    public BigDecimal getIncomerate() {
        return incomerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.incomerate
     *
     * @param incomerate the value for public.rank_ext_balance.incomerate
     *
     * @mbg.generated
     */
    public void setIncomerate(BigDecimal incomerate) {
        this.incomerate = incomerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.avg_incomeamt
     *
     * @return the value of public.rank_ext_balance.avg_incomeamt
     *
     * @mbg.generated
     */
    public Integer getAvgIncomeamt() {
        return avgIncomeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.avg_incomeamt
     *
     * @param avgIncomeamt the value for public.rank_ext_balance.avg_incomeamt
     *
     * @mbg.generated
     */
    public void setAvgIncomeamt(Integer avgIncomeamt) {
        this.avgIncomeamt = avgIncomeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.extkey
     *
     * @return the value of public.rank_ext_balance.extkey
     *
     * @mbg.generated
     */
    public String getExtkey() {
        return extkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.extkey
     *
     * @param extkey the value for public.rank_ext_balance.extkey
     *
     * @mbg.generated
     */
    public void setExtkey(String extkey) {
        this.extkey = extkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.rank_ext_balance.balance
     *
     * @return the value of public.rank_ext_balance.balance
     *
     * @mbg.generated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.rank_ext_balance.balance
     *
     * @param balance the value for public.rank_ext_balance.balance
     *
     * @mbg.generated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}