package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;

public class RecRaceWaku2 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.ymd
	 * @mbg.generated
	 */
	private String ymd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.jyocd
	 * @mbg.generated
	 */
	private String jyocd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.raceno
	 * @mbg.generated
	 */
	private Short raceno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nationwiningrate1
	 * @mbg.generated
	 */
	private BigDecimal nationwiningrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nationwiningrate2
	 * @mbg.generated
	 */
	private BigDecimal nationwiningrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nationwiningrate3
	 * @mbg.generated
	 */
	private BigDecimal nationwiningrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nationwiningrate4
	 * @mbg.generated
	 */
	private BigDecimal nationwiningrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nationwiningrate5
	 * @mbg.generated
	 */
	private BigDecimal nationwiningrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nationwiningrate6
	 * @mbg.generated
	 */
	private BigDecimal nationwiningrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation2winingrate1
	 * @mbg.generated
	 */
	private BigDecimal nation2winingrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation2winingrate2
	 * @mbg.generated
	 */
	private BigDecimal nation2winingrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation2winingrate3
	 * @mbg.generated
	 */
	private BigDecimal nation2winingrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation2winingrate4
	 * @mbg.generated
	 */
	private BigDecimal nation2winingrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation2winingrate5
	 * @mbg.generated
	 */
	private BigDecimal nation2winingrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation2winingrate6
	 * @mbg.generated
	 */
	private BigDecimal nation2winingrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation3winingrate1
	 * @mbg.generated
	 */
	private BigDecimal nation3winingrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation3winingrate2
	 * @mbg.generated
	 */
	private BigDecimal nation3winingrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation3winingrate3
	 * @mbg.generated
	 */
	private BigDecimal nation3winingrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation3winingrate4
	 * @mbg.generated
	 */
	private BigDecimal nation3winingrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation3winingrate5
	 * @mbg.generated
	 */
	private BigDecimal nation3winingrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.nation3winingrate6
	 * @mbg.generated
	 */
	private BigDecimal nation3winingrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.localwiningrate1
	 * @mbg.generated
	 */
	private BigDecimal localwiningrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.localwiningrate2
	 * @mbg.generated
	 */
	private BigDecimal localwiningrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.localwiningrate3
	 * @mbg.generated
	 */
	private BigDecimal localwiningrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.localwiningrate4
	 * @mbg.generated
	 */
	private BigDecimal localwiningrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.localwiningrate5
	 * @mbg.generated
	 */
	private BigDecimal localwiningrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.localwiningrate6
	 * @mbg.generated
	 */
	private BigDecimal localwiningrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local2winingrate1
	 * @mbg.generated
	 */
	private BigDecimal local2winingrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local2winingrate2
	 * @mbg.generated
	 */
	private BigDecimal local2winingrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local2winingrate3
	 * @mbg.generated
	 */
	private BigDecimal local2winingrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local2winingrate4
	 * @mbg.generated
	 */
	private BigDecimal local2winingrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local2winingrate5
	 * @mbg.generated
	 */
	private BigDecimal local2winingrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local2winingrate6
	 * @mbg.generated
	 */
	private BigDecimal local2winingrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local3winingrate1
	 * @mbg.generated
	 */
	private BigDecimal local3winingrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local3winingrate2
	 * @mbg.generated
	 */
	private BigDecimal local3winingrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local3winingrate3
	 * @mbg.generated
	 */
	private BigDecimal local3winingrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local3winingrate4
	 * @mbg.generated
	 */
	private BigDecimal local3winingrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local3winingrate5
	 * @mbg.generated
	 */
	private BigDecimal local3winingrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.local3winingrate6
	 * @mbg.generated
	 */
	private BigDecimal local3winingrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor2winingrate1
	 * @mbg.generated
	 */
	private BigDecimal motor2winingrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor2winingrate2
	 * @mbg.generated
	 */
	private BigDecimal motor2winingrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor2winingrate3
	 * @mbg.generated
	 */
	private BigDecimal motor2winingrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor2winingrate4
	 * @mbg.generated
	 */
	private BigDecimal motor2winingrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor2winingrate5
	 * @mbg.generated
	 */
	private BigDecimal motor2winingrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor2winingrate6
	 * @mbg.generated
	 */
	private BigDecimal motor2winingrate6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor3winingrate1
	 * @mbg.generated
	 */
	private BigDecimal motor3winingrate1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor3winingrate2
	 * @mbg.generated
	 */
	private BigDecimal motor3winingrate2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor3winingrate3
	 * @mbg.generated
	 */
	private BigDecimal motor3winingrate3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor3winingrate4
	 * @mbg.generated
	 */
	private BigDecimal motor3winingrate4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor3winingrate5
	 * @mbg.generated
	 */
	private BigDecimal motor3winingrate5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_waku2.motor3winingrate6
	 * @mbg.generated
	 */
	private BigDecimal motor3winingrate6;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.ymd
	 * @return  the value of public.rec_race_waku2.ymd
	 * @mbg.generated
	 */
	public String getYmd() {
		return ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.ymd
	 * @param ymd  the value for public.rec_race_waku2.ymd
	 * @mbg.generated
	 */
	public void setYmd(String ymd) {
		this.ymd = ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.jyocd
	 * @return  the value of public.rec_race_waku2.jyocd
	 * @mbg.generated
	 */
	public String getJyocd() {
		return jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.jyocd
	 * @param jyocd  the value for public.rec_race_waku2.jyocd
	 * @mbg.generated
	 */
	public void setJyocd(String jyocd) {
		this.jyocd = jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.raceno
	 * @return  the value of public.rec_race_waku2.raceno
	 * @mbg.generated
	 */
	public Short getRaceno() {
		return raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.raceno
	 * @param raceno  the value for public.rec_race_waku2.raceno
	 * @mbg.generated
	 */
	public void setRaceno(Short raceno) {
		this.raceno = raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nationwiningrate1
	 * @return  the value of public.rec_race_waku2.nationwiningrate1
	 * @mbg.generated
	 */
	public BigDecimal getNationwiningrate1() {
		return nationwiningrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nationwiningrate1
	 * @param nationwiningrate1  the value for public.rec_race_waku2.nationwiningrate1
	 * @mbg.generated
	 */
	public void setNationwiningrate1(BigDecimal nationwiningrate1) {
		this.nationwiningrate1 = nationwiningrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nationwiningrate2
	 * @return  the value of public.rec_race_waku2.nationwiningrate2
	 * @mbg.generated
	 */
	public BigDecimal getNationwiningrate2() {
		return nationwiningrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nationwiningrate2
	 * @param nationwiningrate2  the value for public.rec_race_waku2.nationwiningrate2
	 * @mbg.generated
	 */
	public void setNationwiningrate2(BigDecimal nationwiningrate2) {
		this.nationwiningrate2 = nationwiningrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nationwiningrate3
	 * @return  the value of public.rec_race_waku2.nationwiningrate3
	 * @mbg.generated
	 */
	public BigDecimal getNationwiningrate3() {
		return nationwiningrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nationwiningrate3
	 * @param nationwiningrate3  the value for public.rec_race_waku2.nationwiningrate3
	 * @mbg.generated
	 */
	public void setNationwiningrate3(BigDecimal nationwiningrate3) {
		this.nationwiningrate3 = nationwiningrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nationwiningrate4
	 * @return  the value of public.rec_race_waku2.nationwiningrate4
	 * @mbg.generated
	 */
	public BigDecimal getNationwiningrate4() {
		return nationwiningrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nationwiningrate4
	 * @param nationwiningrate4  the value for public.rec_race_waku2.nationwiningrate4
	 * @mbg.generated
	 */
	public void setNationwiningrate4(BigDecimal nationwiningrate4) {
		this.nationwiningrate4 = nationwiningrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nationwiningrate5
	 * @return  the value of public.rec_race_waku2.nationwiningrate5
	 * @mbg.generated
	 */
	public BigDecimal getNationwiningrate5() {
		return nationwiningrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nationwiningrate5
	 * @param nationwiningrate5  the value for public.rec_race_waku2.nationwiningrate5
	 * @mbg.generated
	 */
	public void setNationwiningrate5(BigDecimal nationwiningrate5) {
		this.nationwiningrate5 = nationwiningrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nationwiningrate6
	 * @return  the value of public.rec_race_waku2.nationwiningrate6
	 * @mbg.generated
	 */
	public BigDecimal getNationwiningrate6() {
		return nationwiningrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nationwiningrate6
	 * @param nationwiningrate6  the value for public.rec_race_waku2.nationwiningrate6
	 * @mbg.generated
	 */
	public void setNationwiningrate6(BigDecimal nationwiningrate6) {
		this.nationwiningrate6 = nationwiningrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation2winingrate1
	 * @return  the value of public.rec_race_waku2.nation2winingrate1
	 * @mbg.generated
	 */
	public BigDecimal getNation2winingrate1() {
		return nation2winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation2winingrate1
	 * @param nation2winingrate1  the value for public.rec_race_waku2.nation2winingrate1
	 * @mbg.generated
	 */
	public void setNation2winingrate1(BigDecimal nation2winingrate1) {
		this.nation2winingrate1 = nation2winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation2winingrate2
	 * @return  the value of public.rec_race_waku2.nation2winingrate2
	 * @mbg.generated
	 */
	public BigDecimal getNation2winingrate2() {
		return nation2winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation2winingrate2
	 * @param nation2winingrate2  the value for public.rec_race_waku2.nation2winingrate2
	 * @mbg.generated
	 */
	public void setNation2winingrate2(BigDecimal nation2winingrate2) {
		this.nation2winingrate2 = nation2winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation2winingrate3
	 * @return  the value of public.rec_race_waku2.nation2winingrate3
	 * @mbg.generated
	 */
	public BigDecimal getNation2winingrate3() {
		return nation2winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation2winingrate3
	 * @param nation2winingrate3  the value for public.rec_race_waku2.nation2winingrate3
	 * @mbg.generated
	 */
	public void setNation2winingrate3(BigDecimal nation2winingrate3) {
		this.nation2winingrate3 = nation2winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation2winingrate4
	 * @return  the value of public.rec_race_waku2.nation2winingrate4
	 * @mbg.generated
	 */
	public BigDecimal getNation2winingrate4() {
		return nation2winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation2winingrate4
	 * @param nation2winingrate4  the value for public.rec_race_waku2.nation2winingrate4
	 * @mbg.generated
	 */
	public void setNation2winingrate4(BigDecimal nation2winingrate4) {
		this.nation2winingrate4 = nation2winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation2winingrate5
	 * @return  the value of public.rec_race_waku2.nation2winingrate5
	 * @mbg.generated
	 */
	public BigDecimal getNation2winingrate5() {
		return nation2winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation2winingrate5
	 * @param nation2winingrate5  the value for public.rec_race_waku2.nation2winingrate5
	 * @mbg.generated
	 */
	public void setNation2winingrate5(BigDecimal nation2winingrate5) {
		this.nation2winingrate5 = nation2winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation2winingrate6
	 * @return  the value of public.rec_race_waku2.nation2winingrate6
	 * @mbg.generated
	 */
	public BigDecimal getNation2winingrate6() {
		return nation2winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation2winingrate6
	 * @param nation2winingrate6  the value for public.rec_race_waku2.nation2winingrate6
	 * @mbg.generated
	 */
	public void setNation2winingrate6(BigDecimal nation2winingrate6) {
		this.nation2winingrate6 = nation2winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation3winingrate1
	 * @return  the value of public.rec_race_waku2.nation3winingrate1
	 * @mbg.generated
	 */
	public BigDecimal getNation3winingrate1() {
		return nation3winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation3winingrate1
	 * @param nation3winingrate1  the value for public.rec_race_waku2.nation3winingrate1
	 * @mbg.generated
	 */
	public void setNation3winingrate1(BigDecimal nation3winingrate1) {
		this.nation3winingrate1 = nation3winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation3winingrate2
	 * @return  the value of public.rec_race_waku2.nation3winingrate2
	 * @mbg.generated
	 */
	public BigDecimal getNation3winingrate2() {
		return nation3winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation3winingrate2
	 * @param nation3winingrate2  the value for public.rec_race_waku2.nation3winingrate2
	 * @mbg.generated
	 */
	public void setNation3winingrate2(BigDecimal nation3winingrate2) {
		this.nation3winingrate2 = nation3winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation3winingrate3
	 * @return  the value of public.rec_race_waku2.nation3winingrate3
	 * @mbg.generated
	 */
	public BigDecimal getNation3winingrate3() {
		return nation3winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation3winingrate3
	 * @param nation3winingrate3  the value for public.rec_race_waku2.nation3winingrate3
	 * @mbg.generated
	 */
	public void setNation3winingrate3(BigDecimal nation3winingrate3) {
		this.nation3winingrate3 = nation3winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation3winingrate4
	 * @return  the value of public.rec_race_waku2.nation3winingrate4
	 * @mbg.generated
	 */
	public BigDecimal getNation3winingrate4() {
		return nation3winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation3winingrate4
	 * @param nation3winingrate4  the value for public.rec_race_waku2.nation3winingrate4
	 * @mbg.generated
	 */
	public void setNation3winingrate4(BigDecimal nation3winingrate4) {
		this.nation3winingrate4 = nation3winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation3winingrate5
	 * @return  the value of public.rec_race_waku2.nation3winingrate5
	 * @mbg.generated
	 */
	public BigDecimal getNation3winingrate5() {
		return nation3winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation3winingrate5
	 * @param nation3winingrate5  the value for public.rec_race_waku2.nation3winingrate5
	 * @mbg.generated
	 */
	public void setNation3winingrate5(BigDecimal nation3winingrate5) {
		this.nation3winingrate5 = nation3winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.nation3winingrate6
	 * @return  the value of public.rec_race_waku2.nation3winingrate6
	 * @mbg.generated
	 */
	public BigDecimal getNation3winingrate6() {
		return nation3winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.nation3winingrate6
	 * @param nation3winingrate6  the value for public.rec_race_waku2.nation3winingrate6
	 * @mbg.generated
	 */
	public void setNation3winingrate6(BigDecimal nation3winingrate6) {
		this.nation3winingrate6 = nation3winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.localwiningrate1
	 * @return  the value of public.rec_race_waku2.localwiningrate1
	 * @mbg.generated
	 */
	public BigDecimal getLocalwiningrate1() {
		return localwiningrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.localwiningrate1
	 * @param localwiningrate1  the value for public.rec_race_waku2.localwiningrate1
	 * @mbg.generated
	 */
	public void setLocalwiningrate1(BigDecimal localwiningrate1) {
		this.localwiningrate1 = localwiningrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.localwiningrate2
	 * @return  the value of public.rec_race_waku2.localwiningrate2
	 * @mbg.generated
	 */
	public BigDecimal getLocalwiningrate2() {
		return localwiningrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.localwiningrate2
	 * @param localwiningrate2  the value for public.rec_race_waku2.localwiningrate2
	 * @mbg.generated
	 */
	public void setLocalwiningrate2(BigDecimal localwiningrate2) {
		this.localwiningrate2 = localwiningrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.localwiningrate3
	 * @return  the value of public.rec_race_waku2.localwiningrate3
	 * @mbg.generated
	 */
	public BigDecimal getLocalwiningrate3() {
		return localwiningrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.localwiningrate3
	 * @param localwiningrate3  the value for public.rec_race_waku2.localwiningrate3
	 * @mbg.generated
	 */
	public void setLocalwiningrate3(BigDecimal localwiningrate3) {
		this.localwiningrate3 = localwiningrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.localwiningrate4
	 * @return  the value of public.rec_race_waku2.localwiningrate4
	 * @mbg.generated
	 */
	public BigDecimal getLocalwiningrate4() {
		return localwiningrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.localwiningrate4
	 * @param localwiningrate4  the value for public.rec_race_waku2.localwiningrate4
	 * @mbg.generated
	 */
	public void setLocalwiningrate4(BigDecimal localwiningrate4) {
		this.localwiningrate4 = localwiningrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.localwiningrate5
	 * @return  the value of public.rec_race_waku2.localwiningrate5
	 * @mbg.generated
	 */
	public BigDecimal getLocalwiningrate5() {
		return localwiningrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.localwiningrate5
	 * @param localwiningrate5  the value for public.rec_race_waku2.localwiningrate5
	 * @mbg.generated
	 */
	public void setLocalwiningrate5(BigDecimal localwiningrate5) {
		this.localwiningrate5 = localwiningrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.localwiningrate6
	 * @return  the value of public.rec_race_waku2.localwiningrate6
	 * @mbg.generated
	 */
	public BigDecimal getLocalwiningrate6() {
		return localwiningrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.localwiningrate6
	 * @param localwiningrate6  the value for public.rec_race_waku2.localwiningrate6
	 * @mbg.generated
	 */
	public void setLocalwiningrate6(BigDecimal localwiningrate6) {
		this.localwiningrate6 = localwiningrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local2winingrate1
	 * @return  the value of public.rec_race_waku2.local2winingrate1
	 * @mbg.generated
	 */
	public BigDecimal getLocal2winingrate1() {
		return local2winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local2winingrate1
	 * @param local2winingrate1  the value for public.rec_race_waku2.local2winingrate1
	 * @mbg.generated
	 */
	public void setLocal2winingrate1(BigDecimal local2winingrate1) {
		this.local2winingrate1 = local2winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local2winingrate2
	 * @return  the value of public.rec_race_waku2.local2winingrate2
	 * @mbg.generated
	 */
	public BigDecimal getLocal2winingrate2() {
		return local2winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local2winingrate2
	 * @param local2winingrate2  the value for public.rec_race_waku2.local2winingrate2
	 * @mbg.generated
	 */
	public void setLocal2winingrate2(BigDecimal local2winingrate2) {
		this.local2winingrate2 = local2winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local2winingrate3
	 * @return  the value of public.rec_race_waku2.local2winingrate3
	 * @mbg.generated
	 */
	public BigDecimal getLocal2winingrate3() {
		return local2winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local2winingrate3
	 * @param local2winingrate3  the value for public.rec_race_waku2.local2winingrate3
	 * @mbg.generated
	 */
	public void setLocal2winingrate3(BigDecimal local2winingrate3) {
		this.local2winingrate3 = local2winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local2winingrate4
	 * @return  the value of public.rec_race_waku2.local2winingrate4
	 * @mbg.generated
	 */
	public BigDecimal getLocal2winingrate4() {
		return local2winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local2winingrate4
	 * @param local2winingrate4  the value for public.rec_race_waku2.local2winingrate4
	 * @mbg.generated
	 */
	public void setLocal2winingrate4(BigDecimal local2winingrate4) {
		this.local2winingrate4 = local2winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local2winingrate5
	 * @return  the value of public.rec_race_waku2.local2winingrate5
	 * @mbg.generated
	 */
	public BigDecimal getLocal2winingrate5() {
		return local2winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local2winingrate5
	 * @param local2winingrate5  the value for public.rec_race_waku2.local2winingrate5
	 * @mbg.generated
	 */
	public void setLocal2winingrate5(BigDecimal local2winingrate5) {
		this.local2winingrate5 = local2winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local2winingrate6
	 * @return  the value of public.rec_race_waku2.local2winingrate6
	 * @mbg.generated
	 */
	public BigDecimal getLocal2winingrate6() {
		return local2winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local2winingrate6
	 * @param local2winingrate6  the value for public.rec_race_waku2.local2winingrate6
	 * @mbg.generated
	 */
	public void setLocal2winingrate6(BigDecimal local2winingrate6) {
		this.local2winingrate6 = local2winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local3winingrate1
	 * @return  the value of public.rec_race_waku2.local3winingrate1
	 * @mbg.generated
	 */
	public BigDecimal getLocal3winingrate1() {
		return local3winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local3winingrate1
	 * @param local3winingrate1  the value for public.rec_race_waku2.local3winingrate1
	 * @mbg.generated
	 */
	public void setLocal3winingrate1(BigDecimal local3winingrate1) {
		this.local3winingrate1 = local3winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local3winingrate2
	 * @return  the value of public.rec_race_waku2.local3winingrate2
	 * @mbg.generated
	 */
	public BigDecimal getLocal3winingrate2() {
		return local3winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local3winingrate2
	 * @param local3winingrate2  the value for public.rec_race_waku2.local3winingrate2
	 * @mbg.generated
	 */
	public void setLocal3winingrate2(BigDecimal local3winingrate2) {
		this.local3winingrate2 = local3winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local3winingrate3
	 * @return  the value of public.rec_race_waku2.local3winingrate3
	 * @mbg.generated
	 */
	public BigDecimal getLocal3winingrate3() {
		return local3winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local3winingrate3
	 * @param local3winingrate3  the value for public.rec_race_waku2.local3winingrate3
	 * @mbg.generated
	 */
	public void setLocal3winingrate3(BigDecimal local3winingrate3) {
		this.local3winingrate3 = local3winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local3winingrate4
	 * @return  the value of public.rec_race_waku2.local3winingrate4
	 * @mbg.generated
	 */
	public BigDecimal getLocal3winingrate4() {
		return local3winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local3winingrate4
	 * @param local3winingrate4  the value for public.rec_race_waku2.local3winingrate4
	 * @mbg.generated
	 */
	public void setLocal3winingrate4(BigDecimal local3winingrate4) {
		this.local3winingrate4 = local3winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local3winingrate5
	 * @return  the value of public.rec_race_waku2.local3winingrate5
	 * @mbg.generated
	 */
	public BigDecimal getLocal3winingrate5() {
		return local3winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local3winingrate5
	 * @param local3winingrate5  the value for public.rec_race_waku2.local3winingrate5
	 * @mbg.generated
	 */
	public void setLocal3winingrate5(BigDecimal local3winingrate5) {
		this.local3winingrate5 = local3winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.local3winingrate6
	 * @return  the value of public.rec_race_waku2.local3winingrate6
	 * @mbg.generated
	 */
	public BigDecimal getLocal3winingrate6() {
		return local3winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.local3winingrate6
	 * @param local3winingrate6  the value for public.rec_race_waku2.local3winingrate6
	 * @mbg.generated
	 */
	public void setLocal3winingrate6(BigDecimal local3winingrate6) {
		this.local3winingrate6 = local3winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor2winingrate1
	 * @return  the value of public.rec_race_waku2.motor2winingrate1
	 * @mbg.generated
	 */
	public BigDecimal getMotor2winingrate1() {
		return motor2winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor2winingrate1
	 * @param motor2winingrate1  the value for public.rec_race_waku2.motor2winingrate1
	 * @mbg.generated
	 */
	public void setMotor2winingrate1(BigDecimal motor2winingrate1) {
		this.motor2winingrate1 = motor2winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor2winingrate2
	 * @return  the value of public.rec_race_waku2.motor2winingrate2
	 * @mbg.generated
	 */
	public BigDecimal getMotor2winingrate2() {
		return motor2winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor2winingrate2
	 * @param motor2winingrate2  the value for public.rec_race_waku2.motor2winingrate2
	 * @mbg.generated
	 */
	public void setMotor2winingrate2(BigDecimal motor2winingrate2) {
		this.motor2winingrate2 = motor2winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor2winingrate3
	 * @return  the value of public.rec_race_waku2.motor2winingrate3
	 * @mbg.generated
	 */
	public BigDecimal getMotor2winingrate3() {
		return motor2winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor2winingrate3
	 * @param motor2winingrate3  the value for public.rec_race_waku2.motor2winingrate3
	 * @mbg.generated
	 */
	public void setMotor2winingrate3(BigDecimal motor2winingrate3) {
		this.motor2winingrate3 = motor2winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor2winingrate4
	 * @return  the value of public.rec_race_waku2.motor2winingrate4
	 * @mbg.generated
	 */
	public BigDecimal getMotor2winingrate4() {
		return motor2winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor2winingrate4
	 * @param motor2winingrate4  the value for public.rec_race_waku2.motor2winingrate4
	 * @mbg.generated
	 */
	public void setMotor2winingrate4(BigDecimal motor2winingrate4) {
		this.motor2winingrate4 = motor2winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor2winingrate5
	 * @return  the value of public.rec_race_waku2.motor2winingrate5
	 * @mbg.generated
	 */
	public BigDecimal getMotor2winingrate5() {
		return motor2winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor2winingrate5
	 * @param motor2winingrate5  the value for public.rec_race_waku2.motor2winingrate5
	 * @mbg.generated
	 */
	public void setMotor2winingrate5(BigDecimal motor2winingrate5) {
		this.motor2winingrate5 = motor2winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor2winingrate6
	 * @return  the value of public.rec_race_waku2.motor2winingrate6
	 * @mbg.generated
	 */
	public BigDecimal getMotor2winingrate6() {
		return motor2winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor2winingrate6
	 * @param motor2winingrate6  the value for public.rec_race_waku2.motor2winingrate6
	 * @mbg.generated
	 */
	public void setMotor2winingrate6(BigDecimal motor2winingrate6) {
		this.motor2winingrate6 = motor2winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor3winingrate1
	 * @return  the value of public.rec_race_waku2.motor3winingrate1
	 * @mbg.generated
	 */
	public BigDecimal getMotor3winingrate1() {
		return motor3winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor3winingrate1
	 * @param motor3winingrate1  the value for public.rec_race_waku2.motor3winingrate1
	 * @mbg.generated
	 */
	public void setMotor3winingrate1(BigDecimal motor3winingrate1) {
		this.motor3winingrate1 = motor3winingrate1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor3winingrate2
	 * @return  the value of public.rec_race_waku2.motor3winingrate2
	 * @mbg.generated
	 */
	public BigDecimal getMotor3winingrate2() {
		return motor3winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor3winingrate2
	 * @param motor3winingrate2  the value for public.rec_race_waku2.motor3winingrate2
	 * @mbg.generated
	 */
	public void setMotor3winingrate2(BigDecimal motor3winingrate2) {
		this.motor3winingrate2 = motor3winingrate2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor3winingrate3
	 * @return  the value of public.rec_race_waku2.motor3winingrate3
	 * @mbg.generated
	 */
	public BigDecimal getMotor3winingrate3() {
		return motor3winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor3winingrate3
	 * @param motor3winingrate3  the value for public.rec_race_waku2.motor3winingrate3
	 * @mbg.generated
	 */
	public void setMotor3winingrate3(BigDecimal motor3winingrate3) {
		this.motor3winingrate3 = motor3winingrate3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor3winingrate4
	 * @return  the value of public.rec_race_waku2.motor3winingrate4
	 * @mbg.generated
	 */
	public BigDecimal getMotor3winingrate4() {
		return motor3winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor3winingrate4
	 * @param motor3winingrate4  the value for public.rec_race_waku2.motor3winingrate4
	 * @mbg.generated
	 */
	public void setMotor3winingrate4(BigDecimal motor3winingrate4) {
		this.motor3winingrate4 = motor3winingrate4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor3winingrate5
	 * @return  the value of public.rec_race_waku2.motor3winingrate5
	 * @mbg.generated
	 */
	public BigDecimal getMotor3winingrate5() {
		return motor3winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor3winingrate5
	 * @param motor3winingrate5  the value for public.rec_race_waku2.motor3winingrate5
	 * @mbg.generated
	 */
	public void setMotor3winingrate5(BigDecimal motor3winingrate5) {
		this.motor3winingrate5 = motor3winingrate5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_waku2.motor3winingrate6
	 * @return  the value of public.rec_race_waku2.motor3winingrate6
	 * @mbg.generated
	 */
	public BigDecimal getMotor3winingrate6() {
		return motor3winingrate6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_waku2.motor3winingrate6
	 * @param motor3winingrate6  the value for public.rec_race_waku2.motor3winingrate6
	 * @mbg.generated
	 */
	public void setMotor3winingrate6(BigDecimal motor3winingrate6) {
		this.motor3winingrate6 = motor3winingrate6;
	}
}