package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class StatMlMultiresultExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public StatMlMultiresultExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andYmdIsNull() {
			addCriterion("ymd is null");
			return (Criteria) this;
		}

		public Criteria andYmdIsNotNull() {
			addCriterion("ymd is not null");
			return (Criteria) this;
		}

		public Criteria andYmdEqualTo(String value) {
			addCriterion("ymd =", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotEqualTo(String value) {
			addCriterion("ymd <>", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdGreaterThan(String value) {
			addCriterion("ymd >", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdGreaterThanOrEqualTo(String value) {
			addCriterion("ymd >=", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLessThan(String value) {
			addCriterion("ymd <", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLessThanOrEqualTo(String value) {
			addCriterion("ymd <=", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdLike(String value) {
			addCriterion("ymd like", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotLike(String value) {
			addCriterion("ymd not like", value, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdIn(List<String> values) {
			addCriterion("ymd in", values, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotIn(List<String> values) {
			addCriterion("ymd not in", values, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdBetween(String value1, String value2) {
			addCriterion("ymd between", value1, value2, "ymd");
			return (Criteria) this;
		}

		public Criteria andYmdNotBetween(String value1, String value2) {
			addCriterion("ymd not between", value1, value2, "ymd");
			return (Criteria) this;
		}

		public Criteria andJyocdIsNull() {
			addCriterion("jyocd is null");
			return (Criteria) this;
		}

		public Criteria andJyocdIsNotNull() {
			addCriterion("jyocd is not null");
			return (Criteria) this;
		}

		public Criteria andJyocdEqualTo(String value) {
			addCriterion("jyocd =", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotEqualTo(String value) {
			addCriterion("jyocd <>", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdGreaterThan(String value) {
			addCriterion("jyocd >", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdGreaterThanOrEqualTo(String value) {
			addCriterion("jyocd >=", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLessThan(String value) {
			addCriterion("jyocd <", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLessThanOrEqualTo(String value) {
			addCriterion("jyocd <=", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdLike(String value) {
			addCriterion("jyocd like", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotLike(String value) {
			addCriterion("jyocd not like", value, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdIn(List<String> values) {
			addCriterion("jyocd in", values, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotIn(List<String> values) {
			addCriterion("jyocd not in", values, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdBetween(String value1, String value2) {
			addCriterion("jyocd between", value1, value2, "jyocd");
			return (Criteria) this;
		}

		public Criteria andJyocdNotBetween(String value1, String value2) {
			addCriterion("jyocd not between", value1, value2, "jyocd");
			return (Criteria) this;
		}

		public Criteria andRacenoIsNull() {
			addCriterion("raceno is null");
			return (Criteria) this;
		}

		public Criteria andRacenoIsNotNull() {
			addCriterion("raceno is not null");
			return (Criteria) this;
		}

		public Criteria andRacenoEqualTo(Short value) {
			addCriterion("raceno =", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotEqualTo(Short value) {
			addCriterion("raceno <>", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoGreaterThan(Short value) {
			addCriterion("raceno >", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoGreaterThanOrEqualTo(Short value) {
			addCriterion("raceno >=", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoLessThan(Short value) {
			addCriterion("raceno <", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoLessThanOrEqualTo(Short value) {
			addCriterion("raceno <=", value, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoIn(List<Short> values) {
			addCriterion("raceno in", values, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotIn(List<Short> values) {
			addCriterion("raceno not in", values, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoBetween(Short value1, Short value2) {
			addCriterion("raceno between", value1, value2, "raceno");
			return (Criteria) this;
		}

		public Criteria andRacenoNotBetween(Short value1, Short value2) {
			addCriterion("raceno not between", value1, value2, "raceno");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andBettypeIsNull() {
			addCriterion("bettype is null");
			return (Criteria) this;
		}

		public Criteria andBettypeIsNotNull() {
			addCriterion("bettype is not null");
			return (Criteria) this;
		}

		public Criteria andBettypeEqualTo(String value) {
			addCriterion("bettype =", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotEqualTo(String value) {
			addCriterion("bettype <>", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeGreaterThan(String value) {
			addCriterion("bettype >", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeGreaterThanOrEqualTo(String value) {
			addCriterion("bettype >=", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeLessThan(String value) {
			addCriterion("bettype <", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeLessThanOrEqualTo(String value) {
			addCriterion("bettype <=", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeLike(String value) {
			addCriterion("bettype like", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotLike(String value) {
			addCriterion("bettype not like", value, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeIn(List<String> values) {
			addCriterion("bettype in", values, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotIn(List<String> values) {
			addCriterion("bettype not in", values, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeBetween(String value1, String value2) {
			addCriterion("bettype between", value1, value2, "bettype");
			return (Criteria) this;
		}

		public Criteria andBettypeNotBetween(String value1, String value2) {
			addCriterion("bettype not between", value1, value2, "bettype");
			return (Criteria) this;
		}

		public Criteria andResultKumibanIsNull() {
			addCriterion("result_kumiban is null");
			return (Criteria) this;
		}

		public Criteria andResultKumibanIsNotNull() {
			addCriterion("result_kumiban is not null");
			return (Criteria) this;
		}

		public Criteria andResultKumibanEqualTo(String value) {
			addCriterion("result_kumiban =", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanNotEqualTo(String value) {
			addCriterion("result_kumiban <>", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanGreaterThan(String value) {
			addCriterion("result_kumiban >", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanGreaterThanOrEqualTo(String value) {
			addCriterion("result_kumiban >=", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanLessThan(String value) {
			addCriterion("result_kumiban <", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanLessThanOrEqualTo(String value) {
			addCriterion("result_kumiban <=", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanLike(String value) {
			addCriterion("result_kumiban like", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanNotLike(String value) {
			addCriterion("result_kumiban not like", value, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanIn(List<String> values) {
			addCriterion("result_kumiban in", values, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanNotIn(List<String> values) {
			addCriterion("result_kumiban not in", values, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanBetween(String value1, String value2) {
			addCriterion("result_kumiban between", value1, value2, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultKumibanNotBetween(String value1, String value2) {
			addCriterion("result_kumiban not between", value1, value2, "resultKumiban");
			return (Criteria) this;
		}

		public Criteria andResultOddsIsNull() {
			addCriterion("result_odds is null");
			return (Criteria) this;
		}

		public Criteria andResultOddsIsNotNull() {
			addCriterion("result_odds is not null");
			return (Criteria) this;
		}

		public Criteria andResultOddsEqualTo(BigDecimal value) {
			addCriterion("result_odds =", value, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsNotEqualTo(BigDecimal value) {
			addCriterion("result_odds <>", value, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsGreaterThan(BigDecimal value) {
			addCriterion("result_odds >", value, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("result_odds >=", value, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsLessThan(BigDecimal value) {
			addCriterion("result_odds <", value, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsLessThanOrEqualTo(BigDecimal value) {
			addCriterion("result_odds <=", value, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsIn(List<BigDecimal> values) {
			addCriterion("result_odds in", values, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsNotIn(List<BigDecimal> values) {
			addCriterion("result_odds not in", values, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("result_odds between", value1, value2, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("result_odds not between", value1, value2, "resultOdds");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankIsNull() {
			addCriterion("result_oddsrank is null");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankIsNotNull() {
			addCriterion("result_oddsrank is not null");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankEqualTo(Integer value) {
			addCriterion("result_oddsrank =", value, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankNotEqualTo(Integer value) {
			addCriterion("result_oddsrank <>", value, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankGreaterThan(Integer value) {
			addCriterion("result_oddsrank >", value, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankGreaterThanOrEqualTo(Integer value) {
			addCriterion("result_oddsrank >=", value, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankLessThan(Integer value) {
			addCriterion("result_oddsrank <", value, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankLessThanOrEqualTo(Integer value) {
			addCriterion("result_oddsrank <=", value, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankIn(List<Integer> values) {
			addCriterion("result_oddsrank in", values, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankNotIn(List<Integer> values) {
			addCriterion("result_oddsrank not in", values, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankBetween(Integer value1, Integer value2) {
			addCriterion("result_oddsrank between", value1, value2, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andResultOddsrankNotBetween(Integer value1, Integer value2) {
			addCriterion("result_oddsrank not between", value1, value2, "resultOddsrank");
			return (Criteria) this;
		}

		public Criteria andModelnoIsNull() {
			addCriterion("modelno is null");
			return (Criteria) this;
		}

		public Criteria andModelnoIsNotNull() {
			addCriterion("modelno is not null");
			return (Criteria) this;
		}

		public Criteria andModelnoEqualTo(String value) {
			addCriterion("modelno =", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotEqualTo(String value) {
			addCriterion("modelno <>", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoGreaterThan(String value) {
			addCriterion("modelno >", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoGreaterThanOrEqualTo(String value) {
			addCriterion("modelno >=", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoLessThan(String value) {
			addCriterion("modelno <", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoLessThanOrEqualTo(String value) {
			addCriterion("modelno <=", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoLike(String value) {
			addCriterion("modelno like", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotLike(String value) {
			addCriterion("modelno not like", value, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoIn(List<String> values) {
			addCriterion("modelno in", values, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotIn(List<String> values) {
			addCriterion("modelno not in", values, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoBetween(String value1, String value2) {
			addCriterion("modelno between", value1, value2, "modelno");
			return (Criteria) this;
		}

		public Criteria andModelnoNotBetween(String value1, String value2) {
			addCriterion("modelno not between", value1, value2, "modelno");
			return (Criteria) this;
		}

		public Criteria andBetKumibanIsNull() {
			addCriterion("bet_kumiban is null");
			return (Criteria) this;
		}

		public Criteria andBetKumibanIsNotNull() {
			addCriterion("bet_kumiban is not null");
			return (Criteria) this;
		}

		public Criteria andBetKumibanEqualTo(String value) {
			addCriterion("bet_kumiban =", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanNotEqualTo(String value) {
			addCriterion("bet_kumiban <>", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanGreaterThan(String value) {
			addCriterion("bet_kumiban >", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanGreaterThanOrEqualTo(String value) {
			addCriterion("bet_kumiban >=", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanLessThan(String value) {
			addCriterion("bet_kumiban <", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanLessThanOrEqualTo(String value) {
			addCriterion("bet_kumiban <=", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanLike(String value) {
			addCriterion("bet_kumiban like", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanNotLike(String value) {
			addCriterion("bet_kumiban not like", value, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanIn(List<String> values) {
			addCriterion("bet_kumiban in", values, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanNotIn(List<String> values) {
			addCriterion("bet_kumiban not in", values, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanBetween(String value1, String value2) {
			addCriterion("bet_kumiban between", value1, value2, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetKumibanNotBetween(String value1, String value2) {
			addCriterion("bet_kumiban not between", value1, value2, "betKumiban");
			return (Criteria) this;
		}

		public Criteria andBetOddsIsNull() {
			addCriterion("bet_odds is null");
			return (Criteria) this;
		}

		public Criteria andBetOddsIsNotNull() {
			addCriterion("bet_odds is not null");
			return (Criteria) this;
		}

		public Criteria andBetOddsEqualTo(String value) {
			addCriterion("bet_odds =", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsNotEqualTo(String value) {
			addCriterion("bet_odds <>", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsGreaterThan(String value) {
			addCriterion("bet_odds >", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsGreaterThanOrEqualTo(String value) {
			addCriterion("bet_odds >=", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsLessThan(String value) {
			addCriterion("bet_odds <", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsLessThanOrEqualTo(String value) {
			addCriterion("bet_odds <=", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsLike(String value) {
			addCriterion("bet_odds like", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsNotLike(String value) {
			addCriterion("bet_odds not like", value, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsIn(List<String> values) {
			addCriterion("bet_odds in", values, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsNotIn(List<String> values) {
			addCriterion("bet_odds not in", values, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsBetween(String value1, String value2) {
			addCriterion("bet_odds between", value1, value2, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsNotBetween(String value1, String value2) {
			addCriterion("bet_odds not between", value1, value2, "betOdds");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankIsNull() {
			addCriterion("bet_oddsrank is null");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankIsNotNull() {
			addCriterion("bet_oddsrank is not null");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankEqualTo(String value) {
			addCriterion("bet_oddsrank =", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankNotEqualTo(String value) {
			addCriterion("bet_oddsrank <>", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankGreaterThan(String value) {
			addCriterion("bet_oddsrank >", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankGreaterThanOrEqualTo(String value) {
			addCriterion("bet_oddsrank >=", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankLessThan(String value) {
			addCriterion("bet_oddsrank <", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankLessThanOrEqualTo(String value) {
			addCriterion("bet_oddsrank <=", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankLike(String value) {
			addCriterion("bet_oddsrank like", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankNotLike(String value) {
			addCriterion("bet_oddsrank not like", value, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankIn(List<String> values) {
			addCriterion("bet_oddsrank in", values, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankNotIn(List<String> values) {
			addCriterion("bet_oddsrank not in", values, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankBetween(String value1, String value2) {
			addCriterion("bet_oddsrank between", value1, value2, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andBetOddsrankNotBetween(String value1, String value2) {
			addCriterion("bet_oddsrank not between", value1, value2, "betOddsrank");
			return (Criteria) this;
		}

		public Criteria andHityIsNull() {
			addCriterion("hity is null");
			return (Criteria) this;
		}

		public Criteria andHityIsNotNull() {
			addCriterion("hity is not null");
			return (Criteria) this;
		}

		public Criteria andHityEqualTo(String value) {
			addCriterion("hity =", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityNotEqualTo(String value) {
			addCriterion("hity <>", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityGreaterThan(String value) {
			addCriterion("hity >", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityGreaterThanOrEqualTo(String value) {
			addCriterion("hity >=", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityLessThan(String value) {
			addCriterion("hity <", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityLessThanOrEqualTo(String value) {
			addCriterion("hity <=", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityLike(String value) {
			addCriterion("hity like", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityNotLike(String value) {
			addCriterion("hity not like", value, "hity");
			return (Criteria) this;
		}

		public Criteria andHityIn(List<String> values) {
			addCriterion("hity in", values, "hity");
			return (Criteria) this;
		}

		public Criteria andHityNotIn(List<String> values) {
			addCriterion("hity not in", values, "hity");
			return (Criteria) this;
		}

		public Criteria andHityBetween(String value1, String value2) {
			addCriterion("hity between", value1, value2, "hity");
			return (Criteria) this;
		}

		public Criteria andHityNotBetween(String value1, String value2) {
			addCriterion("hity not between", value1, value2, "hity");
			return (Criteria) this;
		}

		public Criteria andHitnIsNull() {
			addCriterion("hitn is null");
			return (Criteria) this;
		}

		public Criteria andHitnIsNotNull() {
			addCriterion("hitn is not null");
			return (Criteria) this;
		}

		public Criteria andHitnEqualTo(String value) {
			addCriterion("hitn =", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnNotEqualTo(String value) {
			addCriterion("hitn <>", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnGreaterThan(String value) {
			addCriterion("hitn >", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnGreaterThanOrEqualTo(String value) {
			addCriterion("hitn >=", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnLessThan(String value) {
			addCriterion("hitn <", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnLessThanOrEqualTo(String value) {
			addCriterion("hitn <=", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnLike(String value) {
			addCriterion("hitn like", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnNotLike(String value) {
			addCriterion("hitn not like", value, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnIn(List<String> values) {
			addCriterion("hitn in", values, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnNotIn(List<String> values) {
			addCriterion("hitn not in", values, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnBetween(String value1, String value2) {
			addCriterion("hitn between", value1, value2, "hitn");
			return (Criteria) this;
		}

		public Criteria andHitnNotBetween(String value1, String value2) {
			addCriterion("hitn not between", value1, value2, "hitn");
			return (Criteria) this;
		}

		public Criteria andBetamtIsNull() {
			addCriterion("betamt is null");
			return (Criteria) this;
		}

		public Criteria andBetamtIsNotNull() {
			addCriterion("betamt is not null");
			return (Criteria) this;
		}

		public Criteria andBetamtEqualTo(String value) {
			addCriterion("betamt =", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtNotEqualTo(String value) {
			addCriterion("betamt <>", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtGreaterThan(String value) {
			addCriterion("betamt >", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtGreaterThanOrEqualTo(String value) {
			addCriterion("betamt >=", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtLessThan(String value) {
			addCriterion("betamt <", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtLessThanOrEqualTo(String value) {
			addCriterion("betamt <=", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtLike(String value) {
			addCriterion("betamt like", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtNotLike(String value) {
			addCriterion("betamt not like", value, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtIn(List<String> values) {
			addCriterion("betamt in", values, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtNotIn(List<String> values) {
			addCriterion("betamt not in", values, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtBetween(String value1, String value2) {
			addCriterion("betamt between", value1, value2, "betamt");
			return (Criteria) this;
		}

		public Criteria andBetamtNotBetween(String value1, String value2) {
			addCriterion("betamt not between", value1, value2, "betamt");
			return (Criteria) this;
		}

		public Criteria andHitamtIsNull() {
			addCriterion("hitamt is null");
			return (Criteria) this;
		}

		public Criteria andHitamtIsNotNull() {
			addCriterion("hitamt is not null");
			return (Criteria) this;
		}

		public Criteria andHitamtEqualTo(String value) {
			addCriterion("hitamt =", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtNotEqualTo(String value) {
			addCriterion("hitamt <>", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtGreaterThan(String value) {
			addCriterion("hitamt >", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtGreaterThanOrEqualTo(String value) {
			addCriterion("hitamt >=", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtLessThan(String value) {
			addCriterion("hitamt <", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtLessThanOrEqualTo(String value) {
			addCriterion("hitamt <=", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtLike(String value) {
			addCriterion("hitamt like", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtNotLike(String value) {
			addCriterion("hitamt not like", value, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtIn(List<String> values) {
			addCriterion("hitamt in", values, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtNotIn(List<String> values) {
			addCriterion("hitamt not in", values, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtBetween(String value1, String value2) {
			addCriterion("hitamt between", value1, value2, "hitamt");
			return (Criteria) this;
		}

		public Criteria andHitamtNotBetween(String value1, String value2) {
			addCriterion("hitamt not between", value1, value2, "hitamt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stat_ml_multiresult
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}