package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;

public class StatMlPtnFinal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.bettype
     *
     * @mbg.generated
     */
    private String bettype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.kumiban
     *
     * @mbg.generated
     */
    private String kumiban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.pattern_name
     *
     * @mbg.generated
     */
    private String patternName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.pattern_value
     *
     * @mbg.generated
     */
    private String patternValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.betcnt
     *
     * @mbg.generated
     */
    private Integer betcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.hitcnt
     *
     * @mbg.generated
     */
    private Integer hitcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.betamt
     *
     * @mbg.generated
     */
    private Integer betamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.hitamt
     *
     * @mbg.generated
     */
    private Integer hitamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.incomeamt
     *
     * @mbg.generated
     */
    private Integer incomeamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.betrate
     *
     * @mbg.generated
     */
    private BigDecimal betrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.hitrate
     *
     * @mbg.generated
     */
    private BigDecimal hitrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.incomerate
     *
     * @mbg.generated
     */
    private BigDecimal incomerate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.totalrate
     *
     * @mbg.generated
     */
    private BigDecimal totalrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.betrate_slope
     *
     * @mbg.generated
     */
    private BigDecimal betrateSlope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.hitrate_slope
     *
     * @mbg.generated
     */
    private BigDecimal hitrateSlope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.incomerate_slope
     *
     * @mbg.generated
     */
    private BigDecimal incomerateSlope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.totalrate_slope
     *
     * @mbg.generated
     */
    private BigDecimal totalrateSlope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.daily_bet_count
     *
     * @mbg.generated
     */
    private Integer dailyBetCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.daily_plus_count
     *
     * @mbg.generated
     */
    private Integer dailyPlusCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.daily_plus_rate
     *
     * @mbg.generated
     */
    private BigDecimal dailyPlusRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.monthly_bet_count
     *
     * @mbg.generated
     */
    private Integer monthlyBetCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.monthly_plus_count
     *
     * @mbg.generated
     */
    private Integer monthlyPlusCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.monthly_plus_rate
     *
     * @mbg.generated
     */
    private BigDecimal monthlyPlusRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.stat_ml_ptn_final.stable_years_count
     *
     * @mbg.generated
     */
    private Integer stableYearsCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.description
     *
     * @return the value of public.stat_ml_ptn_final.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.description
     *
     * @param description the value for public.stat_ml_ptn_final.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.bettype
     *
     * @return the value of public.stat_ml_ptn_final.bettype
     *
     * @mbg.generated
     */
    public String getBettype() {
        return bettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.bettype
     *
     * @param bettype the value for public.stat_ml_ptn_final.bettype
     *
     * @mbg.generated
     */
    public void setBettype(String bettype) {
        this.bettype = bettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.kumiban
     *
     * @return the value of public.stat_ml_ptn_final.kumiban
     *
     * @mbg.generated
     */
    public String getKumiban() {
        return kumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.kumiban
     *
     * @param kumiban the value for public.stat_ml_ptn_final.kumiban
     *
     * @mbg.generated
     */
    public void setKumiban(String kumiban) {
        this.kumiban = kumiban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.pattern_name
     *
     * @return the value of public.stat_ml_ptn_final.pattern_name
     *
     * @mbg.generated
     */
    public String getPatternName() {
        return patternName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.pattern_name
     *
     * @param patternName the value for public.stat_ml_ptn_final.pattern_name
     *
     * @mbg.generated
     */
    public void setPatternName(String patternName) {
        this.patternName = patternName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.pattern_value
     *
     * @return the value of public.stat_ml_ptn_final.pattern_value
     *
     * @mbg.generated
     */
    public String getPatternValue() {
        return patternValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.pattern_value
     *
     * @param patternValue the value for public.stat_ml_ptn_final.pattern_value
     *
     * @mbg.generated
     */
    public void setPatternValue(String patternValue) {
        this.patternValue = patternValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.betcnt
     *
     * @return the value of public.stat_ml_ptn_final.betcnt
     *
     * @mbg.generated
     */
    public Integer getBetcnt() {
        return betcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.betcnt
     *
     * @param betcnt the value for public.stat_ml_ptn_final.betcnt
     *
     * @mbg.generated
     */
    public void setBetcnt(Integer betcnt) {
        this.betcnt = betcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.hitcnt
     *
     * @return the value of public.stat_ml_ptn_final.hitcnt
     *
     * @mbg.generated
     */
    public Integer getHitcnt() {
        return hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.hitcnt
     *
     * @param hitcnt the value for public.stat_ml_ptn_final.hitcnt
     *
     * @mbg.generated
     */
    public void setHitcnt(Integer hitcnt) {
        this.hitcnt = hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.betamt
     *
     * @return the value of public.stat_ml_ptn_final.betamt
     *
     * @mbg.generated
     */
    public Integer getBetamt() {
        return betamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.betamt
     *
     * @param betamt the value for public.stat_ml_ptn_final.betamt
     *
     * @mbg.generated
     */
    public void setBetamt(Integer betamt) {
        this.betamt = betamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.hitamt
     *
     * @return the value of public.stat_ml_ptn_final.hitamt
     *
     * @mbg.generated
     */
    public Integer getHitamt() {
        return hitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.hitamt
     *
     * @param hitamt the value for public.stat_ml_ptn_final.hitamt
     *
     * @mbg.generated
     */
    public void setHitamt(Integer hitamt) {
        this.hitamt = hitamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.incomeamt
     *
     * @return the value of public.stat_ml_ptn_final.incomeamt
     *
     * @mbg.generated
     */
    public Integer getIncomeamt() {
        return incomeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.incomeamt
     *
     * @param incomeamt the value for public.stat_ml_ptn_final.incomeamt
     *
     * @mbg.generated
     */
    public void setIncomeamt(Integer incomeamt) {
        this.incomeamt = incomeamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.betrate
     *
     * @return the value of public.stat_ml_ptn_final.betrate
     *
     * @mbg.generated
     */
    public BigDecimal getBetrate() {
        return betrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.betrate
     *
     * @param betrate the value for public.stat_ml_ptn_final.betrate
     *
     * @mbg.generated
     */
    public void setBetrate(BigDecimal betrate) {
        this.betrate = betrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.hitrate
     *
     * @return the value of public.stat_ml_ptn_final.hitrate
     *
     * @mbg.generated
     */
    public BigDecimal getHitrate() {
        return hitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.hitrate
     *
     * @param hitrate the value for public.stat_ml_ptn_final.hitrate
     *
     * @mbg.generated
     */
    public void setHitrate(BigDecimal hitrate) {
        this.hitrate = hitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.incomerate
     *
     * @return the value of public.stat_ml_ptn_final.incomerate
     *
     * @mbg.generated
     */
    public BigDecimal getIncomerate() {
        return incomerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.incomerate
     *
     * @param incomerate the value for public.stat_ml_ptn_final.incomerate
     *
     * @mbg.generated
     */
    public void setIncomerate(BigDecimal incomerate) {
        this.incomerate = incomerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.totalrate
     *
     * @return the value of public.stat_ml_ptn_final.totalrate
     *
     * @mbg.generated
     */
    public BigDecimal getTotalrate() {
        return totalrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.totalrate
     *
     * @param totalrate the value for public.stat_ml_ptn_final.totalrate
     *
     * @mbg.generated
     */
    public void setTotalrate(BigDecimal totalrate) {
        this.totalrate = totalrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.betrate_slope
     *
     * @return the value of public.stat_ml_ptn_final.betrate_slope
     *
     * @mbg.generated
     */
    public BigDecimal getBetrateSlope() {
        return betrateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.betrate_slope
     *
     * @param betrateSlope the value for public.stat_ml_ptn_final.betrate_slope
     *
     * @mbg.generated
     */
    public void setBetrateSlope(BigDecimal betrateSlope) {
        this.betrateSlope = betrateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.hitrate_slope
     *
     * @return the value of public.stat_ml_ptn_final.hitrate_slope
     *
     * @mbg.generated
     */
    public BigDecimal getHitrateSlope() {
        return hitrateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.hitrate_slope
     *
     * @param hitrateSlope the value for public.stat_ml_ptn_final.hitrate_slope
     *
     * @mbg.generated
     */
    public void setHitrateSlope(BigDecimal hitrateSlope) {
        this.hitrateSlope = hitrateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.incomerate_slope
     *
     * @return the value of public.stat_ml_ptn_final.incomerate_slope
     *
     * @mbg.generated
     */
    public BigDecimal getIncomerateSlope() {
        return incomerateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.incomerate_slope
     *
     * @param incomerateSlope the value for public.stat_ml_ptn_final.incomerate_slope
     *
     * @mbg.generated
     */
    public void setIncomerateSlope(BigDecimal incomerateSlope) {
        this.incomerateSlope = incomerateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.totalrate_slope
     *
     * @return the value of public.stat_ml_ptn_final.totalrate_slope
     *
     * @mbg.generated
     */
    public BigDecimal getTotalrateSlope() {
        return totalrateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.totalrate_slope
     *
     * @param totalrateSlope the value for public.stat_ml_ptn_final.totalrate_slope
     *
     * @mbg.generated
     */
    public void setTotalrateSlope(BigDecimal totalrateSlope) {
        this.totalrateSlope = totalrateSlope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.daily_bet_count
     *
     * @return the value of public.stat_ml_ptn_final.daily_bet_count
     *
     * @mbg.generated
     */
    public Integer getDailyBetCount() {
        return dailyBetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.daily_bet_count
     *
     * @param dailyBetCount the value for public.stat_ml_ptn_final.daily_bet_count
     *
     * @mbg.generated
     */
    public void setDailyBetCount(Integer dailyBetCount) {
        this.dailyBetCount = dailyBetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.daily_plus_count
     *
     * @return the value of public.stat_ml_ptn_final.daily_plus_count
     *
     * @mbg.generated
     */
    public Integer getDailyPlusCount() {
        return dailyPlusCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.daily_plus_count
     *
     * @param dailyPlusCount the value for public.stat_ml_ptn_final.daily_plus_count
     *
     * @mbg.generated
     */
    public void setDailyPlusCount(Integer dailyPlusCount) {
        this.dailyPlusCount = dailyPlusCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.daily_plus_rate
     *
     * @return the value of public.stat_ml_ptn_final.daily_plus_rate
     *
     * @mbg.generated
     */
    public BigDecimal getDailyPlusRate() {
        return dailyPlusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.daily_plus_rate
     *
     * @param dailyPlusRate the value for public.stat_ml_ptn_final.daily_plus_rate
     *
     * @mbg.generated
     */
    public void setDailyPlusRate(BigDecimal dailyPlusRate) {
        this.dailyPlusRate = dailyPlusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.monthly_bet_count
     *
     * @return the value of public.stat_ml_ptn_final.monthly_bet_count
     *
     * @mbg.generated
     */
    public Integer getMonthlyBetCount() {
        return monthlyBetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.monthly_bet_count
     *
     * @param monthlyBetCount the value for public.stat_ml_ptn_final.monthly_bet_count
     *
     * @mbg.generated
     */
    public void setMonthlyBetCount(Integer monthlyBetCount) {
        this.monthlyBetCount = monthlyBetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.monthly_plus_count
     *
     * @return the value of public.stat_ml_ptn_final.monthly_plus_count
     *
     * @mbg.generated
     */
    public Integer getMonthlyPlusCount() {
        return monthlyPlusCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.monthly_plus_count
     *
     * @param monthlyPlusCount the value for public.stat_ml_ptn_final.monthly_plus_count
     *
     * @mbg.generated
     */
    public void setMonthlyPlusCount(Integer monthlyPlusCount) {
        this.monthlyPlusCount = monthlyPlusCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.monthly_plus_rate
     *
     * @return the value of public.stat_ml_ptn_final.monthly_plus_rate
     *
     * @mbg.generated
     */
    public BigDecimal getMonthlyPlusRate() {
        return monthlyPlusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.monthly_plus_rate
     *
     * @param monthlyPlusRate the value for public.stat_ml_ptn_final.monthly_plus_rate
     *
     * @mbg.generated
     */
    public void setMonthlyPlusRate(BigDecimal monthlyPlusRate) {
        this.monthlyPlusRate = monthlyPlusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.stat_ml_ptn_final.stable_years_count
     *
     * @return the value of public.stat_ml_ptn_final.stable_years_count
     *
     * @mbg.generated
     */
    public Integer getStableYearsCount() {
        return stableYearsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.stat_ml_ptn_final.stable_years_count
     *
     * @param stableYearsCount the value for public.stat_ml_ptn_final.stable_years_count
     *
     * @mbg.generated
     */
    public void setStableYearsCount(Integer stableYearsCount) {
        this.stableYearsCount = stableYearsCount;
    }
}