package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class StatMlPtnFinalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public StatMlPtnFinalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andBettypeIsNull() {
            addCriterion("bettype is null");
            return (Criteria) this;
        }

        public Criteria andBettypeIsNotNull() {
            addCriterion("bettype is not null");
            return (Criteria) this;
        }

        public Criteria andBettypeEqualTo(String value) {
            addCriterion("bettype =", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeNotEqualTo(String value) {
            addCriterion("bettype <>", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeGreaterThan(String value) {
            addCriterion("bettype >", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeGreaterThanOrEqualTo(String value) {
            addCriterion("bettype >=", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeLessThan(String value) {
            addCriterion("bettype <", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeLessThanOrEqualTo(String value) {
            addCriterion("bettype <=", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeLike(String value) {
            addCriterion("bettype like", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeNotLike(String value) {
            addCriterion("bettype not like", value, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeIn(List<String> values) {
            addCriterion("bettype in", values, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeNotIn(List<String> values) {
            addCriterion("bettype not in", values, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeBetween(String value1, String value2) {
            addCriterion("bettype between", value1, value2, "bettype");
            return (Criteria) this;
        }

        public Criteria andBettypeNotBetween(String value1, String value2) {
            addCriterion("bettype not between", value1, value2, "bettype");
            return (Criteria) this;
        }

        public Criteria andKumibanIsNull() {
            addCriterion("kumiban is null");
            return (Criteria) this;
        }

        public Criteria andKumibanIsNotNull() {
            addCriterion("kumiban is not null");
            return (Criteria) this;
        }

        public Criteria andKumibanEqualTo(String value) {
            addCriterion("kumiban =", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanNotEqualTo(String value) {
            addCriterion("kumiban <>", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanGreaterThan(String value) {
            addCriterion("kumiban >", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanGreaterThanOrEqualTo(String value) {
            addCriterion("kumiban >=", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanLessThan(String value) {
            addCriterion("kumiban <", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanLessThanOrEqualTo(String value) {
            addCriterion("kumiban <=", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanLike(String value) {
            addCriterion("kumiban like", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanNotLike(String value) {
            addCriterion("kumiban not like", value, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanIn(List<String> values) {
            addCriterion("kumiban in", values, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanNotIn(List<String> values) {
            addCriterion("kumiban not in", values, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanBetween(String value1, String value2) {
            addCriterion("kumiban between", value1, value2, "kumiban");
            return (Criteria) this;
        }

        public Criteria andKumibanNotBetween(String value1, String value2) {
            addCriterion("kumiban not between", value1, value2, "kumiban");
            return (Criteria) this;
        }

        public Criteria andPatternNameIsNull() {
            addCriterion("pattern_name is null");
            return (Criteria) this;
        }

        public Criteria andPatternNameIsNotNull() {
            addCriterion("pattern_name is not null");
            return (Criteria) this;
        }

        public Criteria andPatternNameEqualTo(String value) {
            addCriterion("pattern_name =", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotEqualTo(String value) {
            addCriterion("pattern_name <>", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameGreaterThan(String value) {
            addCriterion("pattern_name >", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameGreaterThanOrEqualTo(String value) {
            addCriterion("pattern_name >=", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLessThan(String value) {
            addCriterion("pattern_name <", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLessThanOrEqualTo(String value) {
            addCriterion("pattern_name <=", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameLike(String value) {
            addCriterion("pattern_name like", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotLike(String value) {
            addCriterion("pattern_name not like", value, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameIn(List<String> values) {
            addCriterion("pattern_name in", values, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotIn(List<String> values) {
            addCriterion("pattern_name not in", values, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameBetween(String value1, String value2) {
            addCriterion("pattern_name between", value1, value2, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternNameNotBetween(String value1, String value2) {
            addCriterion("pattern_name not between", value1, value2, "patternName");
            return (Criteria) this;
        }

        public Criteria andPatternValueIsNull() {
            addCriterion("pattern_value is null");
            return (Criteria) this;
        }

        public Criteria andPatternValueIsNotNull() {
            addCriterion("pattern_value is not null");
            return (Criteria) this;
        }

        public Criteria andPatternValueEqualTo(String value) {
            addCriterion("pattern_value =", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueNotEqualTo(String value) {
            addCriterion("pattern_value <>", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueGreaterThan(String value) {
            addCriterion("pattern_value >", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueGreaterThanOrEqualTo(String value) {
            addCriterion("pattern_value >=", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueLessThan(String value) {
            addCriterion("pattern_value <", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueLessThanOrEqualTo(String value) {
            addCriterion("pattern_value <=", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueLike(String value) {
            addCriterion("pattern_value like", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueNotLike(String value) {
            addCriterion("pattern_value not like", value, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueIn(List<String> values) {
            addCriterion("pattern_value in", values, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueNotIn(List<String> values) {
            addCriterion("pattern_value not in", values, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueBetween(String value1, String value2) {
            addCriterion("pattern_value between", value1, value2, "patternValue");
            return (Criteria) this;
        }

        public Criteria andPatternValueNotBetween(String value1, String value2) {
            addCriterion("pattern_value not between", value1, value2, "patternValue");
            return (Criteria) this;
        }

        public Criteria andBetcntIsNull() {
            addCriterion("betcnt is null");
            return (Criteria) this;
        }

        public Criteria andBetcntIsNotNull() {
            addCriterion("betcnt is not null");
            return (Criteria) this;
        }

        public Criteria andBetcntEqualTo(Integer value) {
            addCriterion("betcnt =", value, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntNotEqualTo(Integer value) {
            addCriterion("betcnt <>", value, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntGreaterThan(Integer value) {
            addCriterion("betcnt >", value, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntGreaterThanOrEqualTo(Integer value) {
            addCriterion("betcnt >=", value, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntLessThan(Integer value) {
            addCriterion("betcnt <", value, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntLessThanOrEqualTo(Integer value) {
            addCriterion("betcnt <=", value, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntIn(List<Integer> values) {
            addCriterion("betcnt in", values, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntNotIn(List<Integer> values) {
            addCriterion("betcnt not in", values, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntBetween(Integer value1, Integer value2) {
            addCriterion("betcnt between", value1, value2, "betcnt");
            return (Criteria) this;
        }

        public Criteria andBetcntNotBetween(Integer value1, Integer value2) {
            addCriterion("betcnt not between", value1, value2, "betcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntIsNull() {
            addCriterion("hitcnt is null");
            return (Criteria) this;
        }

        public Criteria andHitcntIsNotNull() {
            addCriterion("hitcnt is not null");
            return (Criteria) this;
        }

        public Criteria andHitcntEqualTo(Integer value) {
            addCriterion("hitcnt =", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntNotEqualTo(Integer value) {
            addCriterion("hitcnt <>", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntGreaterThan(Integer value) {
            addCriterion("hitcnt >", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntGreaterThanOrEqualTo(Integer value) {
            addCriterion("hitcnt >=", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntLessThan(Integer value) {
            addCriterion("hitcnt <", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntLessThanOrEqualTo(Integer value) {
            addCriterion("hitcnt <=", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntIn(List<Integer> values) {
            addCriterion("hitcnt in", values, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntNotIn(List<Integer> values) {
            addCriterion("hitcnt not in", values, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntBetween(Integer value1, Integer value2) {
            addCriterion("hitcnt between", value1, value2, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntNotBetween(Integer value1, Integer value2) {
            addCriterion("hitcnt not between", value1, value2, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andBetamtIsNull() {
            addCriterion("betamt is null");
            return (Criteria) this;
        }

        public Criteria andBetamtIsNotNull() {
            addCriterion("betamt is not null");
            return (Criteria) this;
        }

        public Criteria andBetamtEqualTo(Integer value) {
            addCriterion("betamt =", value, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtNotEqualTo(Integer value) {
            addCriterion("betamt <>", value, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtGreaterThan(Integer value) {
            addCriterion("betamt >", value, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtGreaterThanOrEqualTo(Integer value) {
            addCriterion("betamt >=", value, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtLessThan(Integer value) {
            addCriterion("betamt <", value, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtLessThanOrEqualTo(Integer value) {
            addCriterion("betamt <=", value, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtIn(List<Integer> values) {
            addCriterion("betamt in", values, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtNotIn(List<Integer> values) {
            addCriterion("betamt not in", values, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtBetween(Integer value1, Integer value2) {
            addCriterion("betamt between", value1, value2, "betamt");
            return (Criteria) this;
        }

        public Criteria andBetamtNotBetween(Integer value1, Integer value2) {
            addCriterion("betamt not between", value1, value2, "betamt");
            return (Criteria) this;
        }

        public Criteria andHitamtIsNull() {
            addCriterion("hitamt is null");
            return (Criteria) this;
        }

        public Criteria andHitamtIsNotNull() {
            addCriterion("hitamt is not null");
            return (Criteria) this;
        }

        public Criteria andHitamtEqualTo(Integer value) {
            addCriterion("hitamt =", value, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtNotEqualTo(Integer value) {
            addCriterion("hitamt <>", value, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtGreaterThan(Integer value) {
            addCriterion("hitamt >", value, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtGreaterThanOrEqualTo(Integer value) {
            addCriterion("hitamt >=", value, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtLessThan(Integer value) {
            addCriterion("hitamt <", value, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtLessThanOrEqualTo(Integer value) {
            addCriterion("hitamt <=", value, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtIn(List<Integer> values) {
            addCriterion("hitamt in", values, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtNotIn(List<Integer> values) {
            addCriterion("hitamt not in", values, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtBetween(Integer value1, Integer value2) {
            addCriterion("hitamt between", value1, value2, "hitamt");
            return (Criteria) this;
        }

        public Criteria andHitamtNotBetween(Integer value1, Integer value2) {
            addCriterion("hitamt not between", value1, value2, "hitamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtIsNull() {
            addCriterion("incomeamt is null");
            return (Criteria) this;
        }

        public Criteria andIncomeamtIsNotNull() {
            addCriterion("incomeamt is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeamtEqualTo(Integer value) {
            addCriterion("incomeamt =", value, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtNotEqualTo(Integer value) {
            addCriterion("incomeamt <>", value, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtGreaterThan(Integer value) {
            addCriterion("incomeamt >", value, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtGreaterThanOrEqualTo(Integer value) {
            addCriterion("incomeamt >=", value, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtLessThan(Integer value) {
            addCriterion("incomeamt <", value, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtLessThanOrEqualTo(Integer value) {
            addCriterion("incomeamt <=", value, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtIn(List<Integer> values) {
            addCriterion("incomeamt in", values, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtNotIn(List<Integer> values) {
            addCriterion("incomeamt not in", values, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtBetween(Integer value1, Integer value2) {
            addCriterion("incomeamt between", value1, value2, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andIncomeamtNotBetween(Integer value1, Integer value2) {
            addCriterion("incomeamt not between", value1, value2, "incomeamt");
            return (Criteria) this;
        }

        public Criteria andBetrateIsNull() {
            addCriterion("betrate is null");
            return (Criteria) this;
        }

        public Criteria andBetrateIsNotNull() {
            addCriterion("betrate is not null");
            return (Criteria) this;
        }

        public Criteria andBetrateEqualTo(BigDecimal value) {
            addCriterion("betrate =", value, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateNotEqualTo(BigDecimal value) {
            addCriterion("betrate <>", value, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateGreaterThan(BigDecimal value) {
            addCriterion("betrate >", value, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("betrate >=", value, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateLessThan(BigDecimal value) {
            addCriterion("betrate <", value, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("betrate <=", value, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateIn(List<BigDecimal> values) {
            addCriterion("betrate in", values, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateNotIn(List<BigDecimal> values) {
            addCriterion("betrate not in", values, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betrate between", value1, value2, "betrate");
            return (Criteria) this;
        }

        public Criteria andBetrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betrate not between", value1, value2, "betrate");
            return (Criteria) this;
        }

        public Criteria andHitrateIsNull() {
            addCriterion("hitrate is null");
            return (Criteria) this;
        }

        public Criteria andHitrateIsNotNull() {
            addCriterion("hitrate is not null");
            return (Criteria) this;
        }

        public Criteria andHitrateEqualTo(BigDecimal value) {
            addCriterion("hitrate =", value, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateNotEqualTo(BigDecimal value) {
            addCriterion("hitrate <>", value, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateGreaterThan(BigDecimal value) {
            addCriterion("hitrate >", value, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hitrate >=", value, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateLessThan(BigDecimal value) {
            addCriterion("hitrate <", value, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hitrate <=", value, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateIn(List<BigDecimal> values) {
            addCriterion("hitrate in", values, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateNotIn(List<BigDecimal> values) {
            addCriterion("hitrate not in", values, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hitrate between", value1, value2, "hitrate");
            return (Criteria) this;
        }

        public Criteria andHitrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hitrate not between", value1, value2, "hitrate");
            return (Criteria) this;
        }

        public Criteria andIncomerateIsNull() {
            addCriterion("incomerate is null");
            return (Criteria) this;
        }

        public Criteria andIncomerateIsNotNull() {
            addCriterion("incomerate is not null");
            return (Criteria) this;
        }

        public Criteria andIncomerateEqualTo(BigDecimal value) {
            addCriterion("incomerate =", value, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateNotEqualTo(BigDecimal value) {
            addCriterion("incomerate <>", value, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateGreaterThan(BigDecimal value) {
            addCriterion("incomerate >", value, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("incomerate >=", value, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateLessThan(BigDecimal value) {
            addCriterion("incomerate <", value, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("incomerate <=", value, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateIn(List<BigDecimal> values) {
            addCriterion("incomerate in", values, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateNotIn(List<BigDecimal> values) {
            addCriterion("incomerate not in", values, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("incomerate between", value1, value2, "incomerate");
            return (Criteria) this;
        }

        public Criteria andIncomerateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("incomerate not between", value1, value2, "incomerate");
            return (Criteria) this;
        }

        public Criteria andTotalrateIsNull() {
            addCriterion("totalrate is null");
            return (Criteria) this;
        }

        public Criteria andTotalrateIsNotNull() {
            addCriterion("totalrate is not null");
            return (Criteria) this;
        }

        public Criteria andTotalrateEqualTo(BigDecimal value) {
            addCriterion("totalrate =", value, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateNotEqualTo(BigDecimal value) {
            addCriterion("totalrate <>", value, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateGreaterThan(BigDecimal value) {
            addCriterion("totalrate >", value, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("totalrate >=", value, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateLessThan(BigDecimal value) {
            addCriterion("totalrate <", value, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("totalrate <=", value, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateIn(List<BigDecimal> values) {
            addCriterion("totalrate in", values, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateNotIn(List<BigDecimal> values) {
            addCriterion("totalrate not in", values, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalrate between", value1, value2, "totalrate");
            return (Criteria) this;
        }

        public Criteria andTotalrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalrate not between", value1, value2, "totalrate");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeIsNull() {
            addCriterion("betrate_slope is null");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeIsNotNull() {
            addCriterion("betrate_slope is not null");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeEqualTo(BigDecimal value) {
            addCriterion("betrate_slope =", value, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeNotEqualTo(BigDecimal value) {
            addCriterion("betrate_slope <>", value, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeGreaterThan(BigDecimal value) {
            addCriterion("betrate_slope >", value, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("betrate_slope >=", value, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeLessThan(BigDecimal value) {
            addCriterion("betrate_slope <", value, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("betrate_slope <=", value, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeIn(List<BigDecimal> values) {
            addCriterion("betrate_slope in", values, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeNotIn(List<BigDecimal> values) {
            addCriterion("betrate_slope not in", values, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betrate_slope between", value1, value2, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andBetrateSlopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("betrate_slope not between", value1, value2, "betrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeIsNull() {
            addCriterion("hitrate_slope is null");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeIsNotNull() {
            addCriterion("hitrate_slope is not null");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeEqualTo(BigDecimal value) {
            addCriterion("hitrate_slope =", value, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeNotEqualTo(BigDecimal value) {
            addCriterion("hitrate_slope <>", value, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeGreaterThan(BigDecimal value) {
            addCriterion("hitrate_slope >", value, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hitrate_slope >=", value, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeLessThan(BigDecimal value) {
            addCriterion("hitrate_slope <", value, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hitrate_slope <=", value, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeIn(List<BigDecimal> values) {
            addCriterion("hitrate_slope in", values, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeNotIn(List<BigDecimal> values) {
            addCriterion("hitrate_slope not in", values, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hitrate_slope between", value1, value2, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andHitrateSlopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hitrate_slope not between", value1, value2, "hitrateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeIsNull() {
            addCriterion("incomerate_slope is null");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeIsNotNull() {
            addCriterion("incomerate_slope is not null");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeEqualTo(BigDecimal value) {
            addCriterion("incomerate_slope =", value, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeNotEqualTo(BigDecimal value) {
            addCriterion("incomerate_slope <>", value, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeGreaterThan(BigDecimal value) {
            addCriterion("incomerate_slope >", value, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("incomerate_slope >=", value, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeLessThan(BigDecimal value) {
            addCriterion("incomerate_slope <", value, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("incomerate_slope <=", value, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeIn(List<BigDecimal> values) {
            addCriterion("incomerate_slope in", values, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeNotIn(List<BigDecimal> values) {
            addCriterion("incomerate_slope not in", values, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("incomerate_slope between", value1, value2, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andIncomerateSlopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("incomerate_slope not between", value1, value2, "incomerateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeIsNull() {
            addCriterion("totalrate_slope is null");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeIsNotNull() {
            addCriterion("totalrate_slope is not null");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeEqualTo(BigDecimal value) {
            addCriterion("totalrate_slope =", value, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeNotEqualTo(BigDecimal value) {
            addCriterion("totalrate_slope <>", value, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeGreaterThan(BigDecimal value) {
            addCriterion("totalrate_slope >", value, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("totalrate_slope >=", value, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeLessThan(BigDecimal value) {
            addCriterion("totalrate_slope <", value, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("totalrate_slope <=", value, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeIn(List<BigDecimal> values) {
            addCriterion("totalrate_slope in", values, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeNotIn(List<BigDecimal> values) {
            addCriterion("totalrate_slope not in", values, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalrate_slope between", value1, value2, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andTotalrateSlopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("totalrate_slope not between", value1, value2, "totalrateSlope");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountIsNull() {
            addCriterion("daily_bet_count is null");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountIsNotNull() {
            addCriterion("daily_bet_count is not null");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountEqualTo(Integer value) {
            addCriterion("daily_bet_count =", value, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountNotEqualTo(Integer value) {
            addCriterion("daily_bet_count <>", value, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountGreaterThan(Integer value) {
            addCriterion("daily_bet_count >", value, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("daily_bet_count >=", value, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountLessThan(Integer value) {
            addCriterion("daily_bet_count <", value, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountLessThanOrEqualTo(Integer value) {
            addCriterion("daily_bet_count <=", value, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountIn(List<Integer> values) {
            addCriterion("daily_bet_count in", values, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountNotIn(List<Integer> values) {
            addCriterion("daily_bet_count not in", values, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountBetween(Integer value1, Integer value2) {
            addCriterion("daily_bet_count between", value1, value2, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyBetCountNotBetween(Integer value1, Integer value2) {
            addCriterion("daily_bet_count not between", value1, value2, "dailyBetCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountIsNull() {
            addCriterion("daily_plus_count is null");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountIsNotNull() {
            addCriterion("daily_plus_count is not null");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountEqualTo(Integer value) {
            addCriterion("daily_plus_count =", value, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountNotEqualTo(Integer value) {
            addCriterion("daily_plus_count <>", value, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountGreaterThan(Integer value) {
            addCriterion("daily_plus_count >", value, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("daily_plus_count >=", value, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountLessThan(Integer value) {
            addCriterion("daily_plus_count <", value, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountLessThanOrEqualTo(Integer value) {
            addCriterion("daily_plus_count <=", value, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountIn(List<Integer> values) {
            addCriterion("daily_plus_count in", values, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountNotIn(List<Integer> values) {
            addCriterion("daily_plus_count not in", values, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountBetween(Integer value1, Integer value2) {
            addCriterion("daily_plus_count between", value1, value2, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusCountNotBetween(Integer value1, Integer value2) {
            addCriterion("daily_plus_count not between", value1, value2, "dailyPlusCount");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateIsNull() {
            addCriterion("daily_plus_rate is null");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateIsNotNull() {
            addCriterion("daily_plus_rate is not null");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateEqualTo(BigDecimal value) {
            addCriterion("daily_plus_rate =", value, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateNotEqualTo(BigDecimal value) {
            addCriterion("daily_plus_rate <>", value, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateGreaterThan(BigDecimal value) {
            addCriterion("daily_plus_rate >", value, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("daily_plus_rate >=", value, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateLessThan(BigDecimal value) {
            addCriterion("daily_plus_rate <", value, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("daily_plus_rate <=", value, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateIn(List<BigDecimal> values) {
            addCriterion("daily_plus_rate in", values, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateNotIn(List<BigDecimal> values) {
            addCriterion("daily_plus_rate not in", values, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("daily_plus_rate between", value1, value2, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andDailyPlusRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("daily_plus_rate not between", value1, value2, "dailyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountIsNull() {
            addCriterion("monthly_bet_count is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountIsNotNull() {
            addCriterion("monthly_bet_count is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountEqualTo(Integer value) {
            addCriterion("monthly_bet_count =", value, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountNotEqualTo(Integer value) {
            addCriterion("monthly_bet_count <>", value, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountGreaterThan(Integer value) {
            addCriterion("monthly_bet_count >", value, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("monthly_bet_count >=", value, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountLessThan(Integer value) {
            addCriterion("monthly_bet_count <", value, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountLessThanOrEqualTo(Integer value) {
            addCriterion("monthly_bet_count <=", value, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountIn(List<Integer> values) {
            addCriterion("monthly_bet_count in", values, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountNotIn(List<Integer> values) {
            addCriterion("monthly_bet_count not in", values, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountBetween(Integer value1, Integer value2) {
            addCriterion("monthly_bet_count between", value1, value2, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyBetCountNotBetween(Integer value1, Integer value2) {
            addCriterion("monthly_bet_count not between", value1, value2, "monthlyBetCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountIsNull() {
            addCriterion("monthly_plus_count is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountIsNotNull() {
            addCriterion("monthly_plus_count is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountEqualTo(Integer value) {
            addCriterion("monthly_plus_count =", value, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountNotEqualTo(Integer value) {
            addCriterion("monthly_plus_count <>", value, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountGreaterThan(Integer value) {
            addCriterion("monthly_plus_count >", value, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("monthly_plus_count >=", value, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountLessThan(Integer value) {
            addCriterion("monthly_plus_count <", value, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountLessThanOrEqualTo(Integer value) {
            addCriterion("monthly_plus_count <=", value, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountIn(List<Integer> values) {
            addCriterion("monthly_plus_count in", values, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountNotIn(List<Integer> values) {
            addCriterion("monthly_plus_count not in", values, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountBetween(Integer value1, Integer value2) {
            addCriterion("monthly_plus_count between", value1, value2, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusCountNotBetween(Integer value1, Integer value2) {
            addCriterion("monthly_plus_count not between", value1, value2, "monthlyPlusCount");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateIsNull() {
            addCriterion("monthly_plus_rate is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateIsNotNull() {
            addCriterion("monthly_plus_rate is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateEqualTo(BigDecimal value) {
            addCriterion("monthly_plus_rate =", value, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateNotEqualTo(BigDecimal value) {
            addCriterion("monthly_plus_rate <>", value, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateGreaterThan(BigDecimal value) {
            addCriterion("monthly_plus_rate >", value, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("monthly_plus_rate >=", value, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateLessThan(BigDecimal value) {
            addCriterion("monthly_plus_rate <", value, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("monthly_plus_rate <=", value, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateIn(List<BigDecimal> values) {
            addCriterion("monthly_plus_rate in", values, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateNotIn(List<BigDecimal> values) {
            addCriterion("monthly_plus_rate not in", values, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthly_plus_rate between", value1, value2, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andMonthlyPlusRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("monthly_plus_rate not between", value1, value2, "monthlyPlusRate");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountIsNull() {
            addCriterion("stable_years_count is null");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountIsNotNull() {
            addCriterion("stable_years_count is not null");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountEqualTo(Integer value) {
            addCriterion("stable_years_count =", value, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountNotEqualTo(Integer value) {
            addCriterion("stable_years_count <>", value, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountGreaterThan(Integer value) {
            addCriterion("stable_years_count >", value, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("stable_years_count >=", value, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountLessThan(Integer value) {
            addCriterion("stable_years_count <", value, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountLessThanOrEqualTo(Integer value) {
            addCriterion("stable_years_count <=", value, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountIn(List<Integer> values) {
            addCriterion("stable_years_count in", values, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountNotIn(List<Integer> values) {
            addCriterion("stable_years_count not in", values, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountBetween(Integer value1, Integer value2) {
            addCriterion("stable_years_count between", value1, value2, "stableYearsCount");
            return (Criteria) this;
        }

        public Criteria andStableYearsCountNotBetween(Integer value1, Integer value2) {
            addCriterion("stable_years_count not between", value1, value2, "stableYearsCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.stat_ml_ptn_final
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}