package com.pengkong.boatrace.mybatis.entity;

public class StatMlResultWekaptn {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.ymd
	 * @mbg.generated
	 */
	private String ymd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.jyocd
	 * @mbg.generated
	 */
	private String jyocd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.raceno
	 * @mbg.generated
	 */
	private Short raceno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.bettype
	 * @mbg.generated
	 */
	private String bettype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.bet_kumiban
	 * @mbg.generated
	 */
	private String betKumiban;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.pattern_name
	 * @mbg.generated
	 */
	private String patternName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.stat_ml_result_wekaptn.pattern_value
	 * @mbg.generated
	 */
	private String patternValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.ymd
	 * @return  the value of public.stat_ml_result_wekaptn.ymd
	 * @mbg.generated
	 */
	public String getYmd() {
		return ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.ymd
	 * @param ymd  the value for public.stat_ml_result_wekaptn.ymd
	 * @mbg.generated
	 */
	public void setYmd(String ymd) {
		this.ymd = ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.jyocd
	 * @return  the value of public.stat_ml_result_wekaptn.jyocd
	 * @mbg.generated
	 */
	public String getJyocd() {
		return jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.jyocd
	 * @param jyocd  the value for public.stat_ml_result_wekaptn.jyocd
	 * @mbg.generated
	 */
	public void setJyocd(String jyocd) {
		this.jyocd = jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.raceno
	 * @return  the value of public.stat_ml_result_wekaptn.raceno
	 * @mbg.generated
	 */
	public Short getRaceno() {
		return raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.raceno
	 * @param raceno  the value for public.stat_ml_result_wekaptn.raceno
	 * @mbg.generated
	 */
	public void setRaceno(Short raceno) {
		this.raceno = raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.description
	 * @return  the value of public.stat_ml_result_wekaptn.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.description
	 * @param description  the value for public.stat_ml_result_wekaptn.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.bettype
	 * @return  the value of public.stat_ml_result_wekaptn.bettype
	 * @mbg.generated
	 */
	public String getBettype() {
		return bettype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.bettype
	 * @param bettype  the value for public.stat_ml_result_wekaptn.bettype
	 * @mbg.generated
	 */
	public void setBettype(String bettype) {
		this.bettype = bettype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.bet_kumiban
	 * @return  the value of public.stat_ml_result_wekaptn.bet_kumiban
	 * @mbg.generated
	 */
	public String getBetKumiban() {
		return betKumiban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.bet_kumiban
	 * @param betKumiban  the value for public.stat_ml_result_wekaptn.bet_kumiban
	 * @mbg.generated
	 */
	public void setBetKumiban(String betKumiban) {
		this.betKumiban = betKumiban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.pattern_name
	 * @return  the value of public.stat_ml_result_wekaptn.pattern_name
	 * @mbg.generated
	 */
	public String getPatternName() {
		return patternName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.pattern_name
	 * @param patternName  the value for public.stat_ml_result_wekaptn.pattern_name
	 * @mbg.generated
	 */
	public void setPatternName(String patternName) {
		this.patternName = patternName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.stat_ml_result_wekaptn.pattern_value
	 * @return  the value of public.stat_ml_result_wekaptn.pattern_value
	 * @mbg.generated
	 */
	public String getPatternValue() {
		return patternValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.stat_ml_result_wekaptn.pattern_value
	 * @param patternValue  the value for public.stat_ml_result_wekaptn.pattern_value
	 * @mbg.generated
	 */
	public void setPatternValue(String patternValue) {
		this.patternValue = patternValue;
	}
}