package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.MlBorkEvaluation;
import com.pengkong.boatrace.mybatis.entity.MlBorkEvaluationExample;

public interface MlBorkEvaluationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_bork_evaluation
	 * @mbg.generated
	 */
	int deleteByExample(MlBorkEvaluationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_bork_evaluation
	 * @mbg.generated
	 */
	int insert(MlBorkEvaluation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_bork_evaluation
	 * @mbg.generated
	 */
	int insertSelective(MlBorkEvaluation record);
}