package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.MlEvaluation;
import com.pengkong.boatrace.mybatis.entity.MlEvaluationExample;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface MlEvaluationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_evaluation
	 * @mbg.generated
	 */
	int deleteByExample(MlEvaluationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_evaluation
	 * @mbg.generated
	 */
	int insert(MlEvaluation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_evaluation
	 * @mbg.generated
	 */
	int insertSelective(MlEvaluation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_evaluation
	 * @mbg.generated
	 */
	List<MlEvaluation> selectByExample(MlEvaluationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_evaluation
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") MlEvaluation record, @Param("example") MlEvaluationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_evaluation
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") MlEvaluation record, @Param("example") MlEvaluationExample example);
}