package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.MlRangeEvaluation;
import com.pengkong.boatrace.mybatis.entity.MlRangeEvaluationExample;

public interface MlRangeEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ml_range_evaluation
     *
     * @mbg.generated
     */
    int deleteByExample(MlRangeEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ml_range_evaluation
     *
     * @mbg.generated
     */
    int insert(MlRangeEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ml_range_evaluation
     *
     * @mbg.generated
     */
    int insertSelective(MlRangeEvaluation record);
}