package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.MlResult;
import com.pengkong.boatrace.mybatis.entity.MlResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_result
	 * @mbg.generated
	 */
	int deleteByExample(MlResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_result
	 * @mbg.generated
	 */
	int insert(MlResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_result
	 * @mbg.generated
	 */
	int insertSelective(MlResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_result
	 * @mbg.generated
	 */
	List<MlResult> selectByExample(MlResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_result
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") MlResult record, @Param("example") MlResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.ml_result
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") MlResult record, @Param("example") MlResultExample example);
}