package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.OddsMonitor;
import com.pengkong.boatrace.mybatis.entity.OddsMonitorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OddsMonitorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	int deleteByExample(OddsMonitorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	int insert(OddsMonitor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	int insertSelective(OddsMonitor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	List<OddsMonitor> selectByExample(OddsMonitorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") OddsMonitor record, @Param("example") OddsMonitorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.odds_monitor
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") OddsMonitor record, @Param("example") OddsMonitorExample example);
}