package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RankResult;
import com.pengkong.boatrace.mybatis.entity.RankResultExample;
import java.util.List;

public interface RankResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rank_result
	 * @mbg.generated
	 */
	int deleteByExample(RankResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rank_result
	 * @mbg.generated
	 */
	int insert(RankResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rank_result
	 * @mbg.generated
	 */
	int insertSelective(RankResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rank_result
	 * @mbg.generated
	 */
	List<RankResult> selectByExample(RankResultExample example);
}