package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RankExtBalance;
import com.pengkong.boatrace.mybatis.entity.RankExtBalanceExample;
import java.util.List;

public interface RankExtBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rank_ext_balance
     *
     * @mbg.generated
     */
    int deleteByExample(RankExtBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rank_ext_balance
     *
     * @mbg.generated
     */
    int insert(RankExtBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rank_ext_balance
     *
     * @mbg.generated
     */
    int insertSelective(RankExtBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rank_ext_balance
     *
     * @mbg.generated
     */
    List<RankExtBalance> selectByExample(RankExtBalanceExample example);
}