package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RecBodds;
import com.pengkong.boatrace.mybatis.entity.RecBoddsExample;
import java.util.List;

public interface RecBoddsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_bodds
	 * @mbg.generated
	 */
	int deleteByExample(RecBoddsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_bodds
	 * @mbg.generated
	 */
	int insert(RecBodds record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_bodds
	 * @mbg.generated
	 */
	int insertSelective(RecBodds record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_bodds
	 * @mbg.generated
	 */
	List<RecBodds> selectByExample(RecBoddsExample example);
}