package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RecFame;
import com.pengkong.boatrace.mybatis.entity.RecFameExample;
import java.util.List;

public interface RecFameMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_fame
	 * @mbg.generated
	 */
	int deleteByExample(RecFameExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_fame
	 * @mbg.generated
	 */
	int insert(RecFame record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_fame
	 * @mbg.generated
	 */
	int insertSelective(RecFame record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_fame
	 * @mbg.generated
	 */
	List<RecFame> selectByExample(RecFameExample example);
}