package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RecOdds;
import com.pengkong.boatrace.mybatis.entity.RecOddsExample;
import java.util.List;

public interface RecOddsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_odds
	 * @mbg.generated
	 */
	int deleteByExample(RecOddsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_odds
	 * @mbg.generated
	 */
	int insert(RecOdds record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_odds
	 * @mbg.generated
	 */
	int insertSelective(RecOdds record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_odds
	 * @mbg.generated
	 */
	List<RecOdds> selectByExample(RecOddsExample example);
}