package com.pengkong.boatrace.mybatis.client;

import java.util.List;

import com.pengkong.boatrace.mybatis.entity.RecRacer;
import com.pengkong.boatrace.mybatis.entity.RecRacerExample;
import com.pengkong.boatrace.mybatis.entity.ex.RecRacerEx;

public interface RecRacerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_racer
	 * @mbg.generated
	 */
	int deleteByExample(RecRacerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_racer
	 * @mbg.generated
	 */
	int insert(RecRacer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_racer
	 * @mbg.generated
	 */
	int insertSelective(RecRacer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_racer
	 * @mbg.generated
	 */
	List<RecRacer> selectByExample(RecRacerExample example);
}