package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RecRacerArrExample;

public interface RecRacerArrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.rec_racer_arr
     *
     * @mbg.generated
     */
    int deleteByExample(RecRacerArrExample example);
}