package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RunRankResultPtn;
import com.pengkong.boatrace.mybatis.entity.RunRankResultPtnExample;
import java.util.List;

public interface RunRankResultPtnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.run_rank_result_ptn
	 * @mbg.generated
	 */
	int deleteByExample(RunRankResultPtnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.run_rank_result_ptn
	 * @mbg.generated
	 */
	int insert(RunRankResultPtn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.run_rank_result_ptn
	 * @mbg.generated
	 */
	int insertSelective(RunRankResultPtn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.run_rank_result_ptn
	 * @mbg.generated
	 */
	List<RunRankResultPtn> selectByExample(RunRankResultPtnExample example);
}