package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.StatMlMultiresult;
import com.pengkong.boatrace.mybatis.entity.StatMlMultiresultExample;
import java.util.List;

public interface StatMlMultiresultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	int deleteByExample(StatMlMultiresultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	int insert(StatMlMultiresult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	int insertSelective(StatMlMultiresult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.stat_ml_multiresult
	 * @mbg.generated
	 */
	List<StatMlMultiresult> selectByExample(StatMlMultiresultExample example);
}