package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.PowerJyoMotorBettype;
import com.pengkong.boatrace.mybatis.entity.PowerJyoMotorBettypeExample;
import java.util.List;

public interface PowerJyoMotorBettypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.power_jyo_motor_bettype
	 * @mbg.generated
	 */
	List<PowerJyoMotorBettype> selectByExample(PowerJyoMotorBettypeExample example);
}