package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;

import com.pengkong.boatrace.util.BoatUtil;

public class PowerAvgtime {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.ymd
	 * @mbg.generated
	 */
	private String ymd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.avgtime
	 * @mbg.generated
	 */
	private BigDecimal avgtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.wakurank
	 * @mbg.generated
	 */
	private String wakurank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.wakurankcnt
	 * @mbg.generated
	 */
	private Integer wakurankcnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.wakurankrate
	 * @mbg.generated
	 */
	private BigDecimal wakurankrate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.cntrank
	 * @mbg.generated
	 */
	private Short cntrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.raterank
	 * @mbg.generated
	 */
	private Short raterank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.power_avgtime.totalrank
	 * @mbg.generated
	 */
	private Short totalrank;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.ymd
	 * @return  the value of public.power_avgtime.ymd
	 * @mbg.generated
	 */
	public String getYmd() {
		return ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.ymd
	 * @param ymd  the value for public.power_avgtime.ymd
	 * @mbg.generated
	 */
	public void setYmd(String ymd) {
		this.ymd = ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.avgtime
	 * @return  the value of public.power_avgtime.avgtime
	 * @mbg.generated
	 */
	public BigDecimal getAvgtime() {
		return avgtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.avgtime
	 * @param avgtime  the value for public.power_avgtime.avgtime
	 * @mbg.generated
	 */
	public void setAvgtime(BigDecimal avgtime) {
		this.avgtime = avgtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.wakurank
	 * @return  the value of public.power_avgtime.wakurank
	 * @mbg.generated
	 */
	public String getWakurank() {
		return wakurank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.wakurank
	 * @param wakurank  the value for public.power_avgtime.wakurank
	 * @mbg.generated
	 */
	public void setWakurank(String wakurank) {
		this.wakurank = wakurank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.wakurankcnt
	 * @return  the value of public.power_avgtime.wakurankcnt
	 * @mbg.generated
	 */
	public Integer getWakurankcnt() {
		return wakurankcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.wakurankcnt
	 * @param wakurankcnt  the value for public.power_avgtime.wakurankcnt
	 * @mbg.generated
	 */
	public void setWakurankcnt(Integer wakurankcnt) {
		this.wakurankcnt = wakurankcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.wakurankrate
	 * @return  the value of public.power_avgtime.wakurankrate
	 * @mbg.generated
	 */
	public BigDecimal getWakurankrate() {
		return wakurankrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.wakurankrate
	 * @param wakurankrate  the value for public.power_avgtime.wakurankrate
	 * @mbg.generated
	 */
	public void setWakurankrate(BigDecimal wakurankrate) {
		this.wakurankrate = wakurankrate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.cntrank
	 * @return  the value of public.power_avgtime.cntrank
	 * @mbg.generated
	 */
	public Short getCntrank() {
		return cntrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.cntrank
	 * @param cntrank  the value for public.power_avgtime.cntrank
	 * @mbg.generated
	 */
	public void setCntrank(Short cntrank) {
		this.cntrank = cntrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.raterank
	 * @return  the value of public.power_avgtime.raterank
	 * @mbg.generated
	 */
	public Short getRaterank() {
		return raterank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.raterank
	 * @param raterank  the value for public.power_avgtime.raterank
	 * @mbg.generated
	 */
	public void setRaterank(Short raterank) {
		this.raterank = raterank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.power_avgtime.totalrank
	 * @return  the value of public.power_avgtime.totalrank
	 * @mbg.generated
	 */
	public Short getTotalrank() {
		return totalrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.power_avgtime.totalrank
	 * @param totalrank  the value for public.power_avgtime.totalrank
	 * @mbg.generated
	 */
	public void setTotalrank(Short totalrank) {
		this.totalrank = totalrank;
	}

	public static PowerAvgtime fromCsv(String[] token) {
		PowerAvgtime rec = new PowerAvgtime();
		rec.setYmd(token[0]);
		rec.setAvgtime(BoatUtil.toBigDecimal(token[1]));
		rec.setWakurank(token[2]);
		rec.setWakurankcnt(BoatUtil.toInt(token[3]));
		rec.setWakurankrate(BoatUtil.toBigDecimal(token[4]));
		rec.setCntrank(BoatUtil.toShort(token[5]));
		rec.setRaterank(BoatUtil.toShort(token[6]));
		rec.setTotalrank(BoatUtil.toShort(token[7]));
		
		return rec;
	}
	
	public String createKey() {
		return this.ymd + "_" + this.avgtime + "_" + this.wakurank;
	}
}