package com.pengkong.boatrace.mybatis.entity;

import java.math.BigDecimal;

public class RecRace13 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.ymd
	 * @mbg.generated
	 */
	private String ymd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.jyocd
	 * @mbg.generated
	 */
	private String jyocd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.raceno
	 * @mbg.generated
	 */
	private Short raceno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.y
	 * @mbg.generated
	 */
	private Short y;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.m
	 * @mbg.generated
	 */
	private Short m;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.d
	 * @mbg.generated
	 */
	private Short d;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sime
	 * @mbg.generated
	 */
	private String sime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.temparature
	 * @mbg.generated
	 */
	private BigDecimal temparature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.weather
	 * @mbg.generated
	 */
	private String weather;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.winddirection
	 * @mbg.generated
	 */
	private Short winddirection;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.wind
	 * @mbg.generated
	 */
	private BigDecimal wind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.watertemp
	 * @mbg.generated
	 */
	private BigDecimal watertemp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.wave
	 * @mbg.generated
	 */
	private Short wave;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.grade
	 * @mbg.generated
	 */
	private String grade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.isvenus
	 * @mbg.generated
	 */
	private String isvenus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.timezone
	 * @mbg.generated
	 */
	private String timezone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.turn
	 * @mbg.generated
	 */
	private String turn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sanrentanno
	 * @mbg.generated
	 */
	private String sanrentanno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sanrentanprize
	 * @mbg.generated
	 */
	private Integer sanrentanprize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sanrentanpopular
	 * @mbg.generated
	 */
	private Short sanrentanpopular;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sanrenhukuno
	 * @mbg.generated
	 */
	private String sanrenhukuno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sanrenhukuprize
	 * @mbg.generated
	 */
	private Integer sanrenhukuprize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.sanrenhukupopular
	 * @mbg.generated
	 */
	private Short sanrenhukupopular;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nirentanno
	 * @mbg.generated
	 */
	private String nirentanno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nirentanprize
	 * @mbg.generated
	 */
	private Integer nirentanprize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nirentanpopular
	 * @mbg.generated
	 */
	private Short nirentanpopular;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nirenhukuno
	 * @mbg.generated
	 */
	private String nirenhukuno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nirenhukuprize
	 * @mbg.generated
	 */
	private Integer nirenhukuprize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nirenhukupopular
	 * @mbg.generated
	 */
	private Short nirenhukupopular;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.tansyono
	 * @mbg.generated
	 */
	private String tansyono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.tansyoprize
	 * @mbg.generated
	 */
	private Integer tansyoprize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.tansyopopular
	 * @mbg.generated
	 */
	private Short tansyopopular;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.kimarite
	 * @mbg.generated
	 */
	private String kimarite;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.wakurank
	 * @mbg.generated
	 */
	private String wakurank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.levelrank
	 * @mbg.generated
	 */
	private String levelrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.resultlevelrank
	 * @mbg.generated
	 */
	private String resultlevelrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nationwiningrank
	 * @mbg.generated
	 */
	private String nationwiningrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nation2winingrank
	 * @mbg.generated
	 */
	private String nation2winingrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.nation3winingrank
	 * @mbg.generated
	 */
	private String nation3winingrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.localwiningrank
	 * @mbg.generated
	 */
	private String localwiningrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.local2winingrank
	 * @mbg.generated
	 */
	private String local2winingrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.local3winingrank
	 * @mbg.generated
	 */
	private String local3winingrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.motor2rank
	 * @mbg.generated
	 */
	private String motor2rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.motor3rank
	 * @mbg.generated
	 */
	private String motor3rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.startexhibitrank
	 * @mbg.generated
	 */
	private String startexhibitrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.exhibitrank
	 * @mbg.generated
	 */
	private String exhibitrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.averagestartrank
	 * @mbg.generated
	 */
	private String averagestartrank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.fixedentrance
	 * @mbg.generated
	 */
	private String fixedentrance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.racetype
	 * @mbg.generated
	 */
	private String racetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.wakulevellist
	 * @mbg.generated
	 */
	private String wakulevellist;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.alevelcount
	 * @mbg.generated
	 */
	private Short alevelcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column public.rec_race_13.femalecount
	 * @mbg.generated
	 */
	private Short femalecount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.ymd
	 * @return  the value of public.rec_race_13.ymd
	 * @mbg.generated
	 */
	public String getYmd() {
		return ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.ymd
	 * @param ymd  the value for public.rec_race_13.ymd
	 * @mbg.generated
	 */
	public void setYmd(String ymd) {
		this.ymd = ymd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.jyocd
	 * @return  the value of public.rec_race_13.jyocd
	 * @mbg.generated
	 */
	public String getJyocd() {
		return jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.jyocd
	 * @param jyocd  the value for public.rec_race_13.jyocd
	 * @mbg.generated
	 */
	public void setJyocd(String jyocd) {
		this.jyocd = jyocd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.raceno
	 * @return  the value of public.rec_race_13.raceno
	 * @mbg.generated
	 */
	public Short getRaceno() {
		return raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.raceno
	 * @param raceno  the value for public.rec_race_13.raceno
	 * @mbg.generated
	 */
	public void setRaceno(Short raceno) {
		this.raceno = raceno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.y
	 * @return  the value of public.rec_race_13.y
	 * @mbg.generated
	 */
	public Short getY() {
		return y;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.y
	 * @param y  the value for public.rec_race_13.y
	 * @mbg.generated
	 */
	public void setY(Short y) {
		this.y = y;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.m
	 * @return  the value of public.rec_race_13.m
	 * @mbg.generated
	 */
	public Short getM() {
		return m;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.m
	 * @param m  the value for public.rec_race_13.m
	 * @mbg.generated
	 */
	public void setM(Short m) {
		this.m = m;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.d
	 * @return  the value of public.rec_race_13.d
	 * @mbg.generated
	 */
	public Short getD() {
		return d;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.d
	 * @param d  the value for public.rec_race_13.d
	 * @mbg.generated
	 */
	public void setD(Short d) {
		this.d = d;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sime
	 * @return  the value of public.rec_race_13.sime
	 * @mbg.generated
	 */
	public String getSime() {
		return sime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sime
	 * @param sime  the value for public.rec_race_13.sime
	 * @mbg.generated
	 */
	public void setSime(String sime) {
		this.sime = sime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.temparature
	 * @return  the value of public.rec_race_13.temparature
	 * @mbg.generated
	 */
	public BigDecimal getTemparature() {
		return temparature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.temparature
	 * @param temparature  the value for public.rec_race_13.temparature
	 * @mbg.generated
	 */
	public void setTemparature(BigDecimal temparature) {
		this.temparature = temparature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.weather
	 * @return  the value of public.rec_race_13.weather
	 * @mbg.generated
	 */
	public String getWeather() {
		return weather;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.weather
	 * @param weather  the value for public.rec_race_13.weather
	 * @mbg.generated
	 */
	public void setWeather(String weather) {
		this.weather = weather;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.winddirection
	 * @return  the value of public.rec_race_13.winddirection
	 * @mbg.generated
	 */
	public Short getWinddirection() {
		return winddirection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.winddirection
	 * @param winddirection  the value for public.rec_race_13.winddirection
	 * @mbg.generated
	 */
	public void setWinddirection(Short winddirection) {
		this.winddirection = winddirection;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.wind
	 * @return  the value of public.rec_race_13.wind
	 * @mbg.generated
	 */
	public BigDecimal getWind() {
		return wind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.wind
	 * @param wind  the value for public.rec_race_13.wind
	 * @mbg.generated
	 */
	public void setWind(BigDecimal wind) {
		this.wind = wind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.watertemp
	 * @return  the value of public.rec_race_13.watertemp
	 * @mbg.generated
	 */
	public BigDecimal getWatertemp() {
		return watertemp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.watertemp
	 * @param watertemp  the value for public.rec_race_13.watertemp
	 * @mbg.generated
	 */
	public void setWatertemp(BigDecimal watertemp) {
		this.watertemp = watertemp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.wave
	 * @return  the value of public.rec_race_13.wave
	 * @mbg.generated
	 */
	public Short getWave() {
		return wave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.wave
	 * @param wave  the value for public.rec_race_13.wave
	 * @mbg.generated
	 */
	public void setWave(Short wave) {
		this.wave = wave;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.grade
	 * @return  the value of public.rec_race_13.grade
	 * @mbg.generated
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.grade
	 * @param grade  the value for public.rec_race_13.grade
	 * @mbg.generated
	 */
	public void setGrade(String grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.isvenus
	 * @return  the value of public.rec_race_13.isvenus
	 * @mbg.generated
	 */
	public String getIsvenus() {
		return isvenus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.isvenus
	 * @param isvenus  the value for public.rec_race_13.isvenus
	 * @mbg.generated
	 */
	public void setIsvenus(String isvenus) {
		this.isvenus = isvenus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.timezone
	 * @return  the value of public.rec_race_13.timezone
	 * @mbg.generated
	 */
	public String getTimezone() {
		return timezone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.timezone
	 * @param timezone  the value for public.rec_race_13.timezone
	 * @mbg.generated
	 */
	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.turn
	 * @return  the value of public.rec_race_13.turn
	 * @mbg.generated
	 */
	public String getTurn() {
		return turn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.turn
	 * @param turn  the value for public.rec_race_13.turn
	 * @mbg.generated
	 */
	public void setTurn(String turn) {
		this.turn = turn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sanrentanno
	 * @return  the value of public.rec_race_13.sanrentanno
	 * @mbg.generated
	 */
	public String getSanrentanno() {
		return sanrentanno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sanrentanno
	 * @param sanrentanno  the value for public.rec_race_13.sanrentanno
	 * @mbg.generated
	 */
	public void setSanrentanno(String sanrentanno) {
		this.sanrentanno = sanrentanno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sanrentanprize
	 * @return  the value of public.rec_race_13.sanrentanprize
	 * @mbg.generated
	 */
	public Integer getSanrentanprize() {
		return sanrentanprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sanrentanprize
	 * @param sanrentanprize  the value for public.rec_race_13.sanrentanprize
	 * @mbg.generated
	 */
	public void setSanrentanprize(Integer sanrentanprize) {
		this.sanrentanprize = sanrentanprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sanrentanpopular
	 * @return  the value of public.rec_race_13.sanrentanpopular
	 * @mbg.generated
	 */
	public Short getSanrentanpopular() {
		return sanrentanpopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sanrentanpopular
	 * @param sanrentanpopular  the value for public.rec_race_13.sanrentanpopular
	 * @mbg.generated
	 */
	public void setSanrentanpopular(Short sanrentanpopular) {
		this.sanrentanpopular = sanrentanpopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sanrenhukuno
	 * @return  the value of public.rec_race_13.sanrenhukuno
	 * @mbg.generated
	 */
	public String getSanrenhukuno() {
		return sanrenhukuno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sanrenhukuno
	 * @param sanrenhukuno  the value for public.rec_race_13.sanrenhukuno
	 * @mbg.generated
	 */
	public void setSanrenhukuno(String sanrenhukuno) {
		this.sanrenhukuno = sanrenhukuno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sanrenhukuprize
	 * @return  the value of public.rec_race_13.sanrenhukuprize
	 * @mbg.generated
	 */
	public Integer getSanrenhukuprize() {
		return sanrenhukuprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sanrenhukuprize
	 * @param sanrenhukuprize  the value for public.rec_race_13.sanrenhukuprize
	 * @mbg.generated
	 */
	public void setSanrenhukuprize(Integer sanrenhukuprize) {
		this.sanrenhukuprize = sanrenhukuprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.sanrenhukupopular
	 * @return  the value of public.rec_race_13.sanrenhukupopular
	 * @mbg.generated
	 */
	public Short getSanrenhukupopular() {
		return sanrenhukupopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.sanrenhukupopular
	 * @param sanrenhukupopular  the value for public.rec_race_13.sanrenhukupopular
	 * @mbg.generated
	 */
	public void setSanrenhukupopular(Short sanrenhukupopular) {
		this.sanrenhukupopular = sanrenhukupopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nirentanno
	 * @return  the value of public.rec_race_13.nirentanno
	 * @mbg.generated
	 */
	public String getNirentanno() {
		return nirentanno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nirentanno
	 * @param nirentanno  the value for public.rec_race_13.nirentanno
	 * @mbg.generated
	 */
	public void setNirentanno(String nirentanno) {
		this.nirentanno = nirentanno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nirentanprize
	 * @return  the value of public.rec_race_13.nirentanprize
	 * @mbg.generated
	 */
	public Integer getNirentanprize() {
		return nirentanprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nirentanprize
	 * @param nirentanprize  the value for public.rec_race_13.nirentanprize
	 * @mbg.generated
	 */
	public void setNirentanprize(Integer nirentanprize) {
		this.nirentanprize = nirentanprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nirentanpopular
	 * @return  the value of public.rec_race_13.nirentanpopular
	 * @mbg.generated
	 */
	public Short getNirentanpopular() {
		return nirentanpopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nirentanpopular
	 * @param nirentanpopular  the value for public.rec_race_13.nirentanpopular
	 * @mbg.generated
	 */
	public void setNirentanpopular(Short nirentanpopular) {
		this.nirentanpopular = nirentanpopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nirenhukuno
	 * @return  the value of public.rec_race_13.nirenhukuno
	 * @mbg.generated
	 */
	public String getNirenhukuno() {
		return nirenhukuno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nirenhukuno
	 * @param nirenhukuno  the value for public.rec_race_13.nirenhukuno
	 * @mbg.generated
	 */
	public void setNirenhukuno(String nirenhukuno) {
		this.nirenhukuno = nirenhukuno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nirenhukuprize
	 * @return  the value of public.rec_race_13.nirenhukuprize
	 * @mbg.generated
	 */
	public Integer getNirenhukuprize() {
		return nirenhukuprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nirenhukuprize
	 * @param nirenhukuprize  the value for public.rec_race_13.nirenhukuprize
	 * @mbg.generated
	 */
	public void setNirenhukuprize(Integer nirenhukuprize) {
		this.nirenhukuprize = nirenhukuprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nirenhukupopular
	 * @return  the value of public.rec_race_13.nirenhukupopular
	 * @mbg.generated
	 */
	public Short getNirenhukupopular() {
		return nirenhukupopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nirenhukupopular
	 * @param nirenhukupopular  the value for public.rec_race_13.nirenhukupopular
	 * @mbg.generated
	 */
	public void setNirenhukupopular(Short nirenhukupopular) {
		this.nirenhukupopular = nirenhukupopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.tansyono
	 * @return  the value of public.rec_race_13.tansyono
	 * @mbg.generated
	 */
	public String getTansyono() {
		return tansyono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.tansyono
	 * @param tansyono  the value for public.rec_race_13.tansyono
	 * @mbg.generated
	 */
	public void setTansyono(String tansyono) {
		this.tansyono = tansyono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.tansyoprize
	 * @return  the value of public.rec_race_13.tansyoprize
	 * @mbg.generated
	 */
	public Integer getTansyoprize() {
		return tansyoprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.tansyoprize
	 * @param tansyoprize  the value for public.rec_race_13.tansyoprize
	 * @mbg.generated
	 */
	public void setTansyoprize(Integer tansyoprize) {
		this.tansyoprize = tansyoprize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.tansyopopular
	 * @return  the value of public.rec_race_13.tansyopopular
	 * @mbg.generated
	 */
	public Short getTansyopopular() {
		return tansyopopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.tansyopopular
	 * @param tansyopopular  the value for public.rec_race_13.tansyopopular
	 * @mbg.generated
	 */
	public void setTansyopopular(Short tansyopopular) {
		this.tansyopopular = tansyopopular;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.kimarite
	 * @return  the value of public.rec_race_13.kimarite
	 * @mbg.generated
	 */
	public String getKimarite() {
		return kimarite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.kimarite
	 * @param kimarite  the value for public.rec_race_13.kimarite
	 * @mbg.generated
	 */
	public void setKimarite(String kimarite) {
		this.kimarite = kimarite;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.wakurank
	 * @return  the value of public.rec_race_13.wakurank
	 * @mbg.generated
	 */
	public String getWakurank() {
		return wakurank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.wakurank
	 * @param wakurank  the value for public.rec_race_13.wakurank
	 * @mbg.generated
	 */
	public void setWakurank(String wakurank) {
		this.wakurank = wakurank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.levelrank
	 * @return  the value of public.rec_race_13.levelrank
	 * @mbg.generated
	 */
	public String getLevelrank() {
		return levelrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.levelrank
	 * @param levelrank  the value for public.rec_race_13.levelrank
	 * @mbg.generated
	 */
	public void setLevelrank(String levelrank) {
		this.levelrank = levelrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.resultlevelrank
	 * @return  the value of public.rec_race_13.resultlevelrank
	 * @mbg.generated
	 */
	public String getResultlevelrank() {
		return resultlevelrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.resultlevelrank
	 * @param resultlevelrank  the value for public.rec_race_13.resultlevelrank
	 * @mbg.generated
	 */
	public void setResultlevelrank(String resultlevelrank) {
		this.resultlevelrank = resultlevelrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nationwiningrank
	 * @return  the value of public.rec_race_13.nationwiningrank
	 * @mbg.generated
	 */
	public String getNationwiningrank() {
		return nationwiningrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nationwiningrank
	 * @param nationwiningrank  the value for public.rec_race_13.nationwiningrank
	 * @mbg.generated
	 */
	public void setNationwiningrank(String nationwiningrank) {
		this.nationwiningrank = nationwiningrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nation2winingrank
	 * @return  the value of public.rec_race_13.nation2winingrank
	 * @mbg.generated
	 */
	public String getNation2winingrank() {
		return nation2winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nation2winingrank
	 * @param nation2winingrank  the value for public.rec_race_13.nation2winingrank
	 * @mbg.generated
	 */
	public void setNation2winingrank(String nation2winingrank) {
		this.nation2winingrank = nation2winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.nation3winingrank
	 * @return  the value of public.rec_race_13.nation3winingrank
	 * @mbg.generated
	 */
	public String getNation3winingrank() {
		return nation3winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.nation3winingrank
	 * @param nation3winingrank  the value for public.rec_race_13.nation3winingrank
	 * @mbg.generated
	 */
	public void setNation3winingrank(String nation3winingrank) {
		this.nation3winingrank = nation3winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.localwiningrank
	 * @return  the value of public.rec_race_13.localwiningrank
	 * @mbg.generated
	 */
	public String getLocalwiningrank() {
		return localwiningrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.localwiningrank
	 * @param localwiningrank  the value for public.rec_race_13.localwiningrank
	 * @mbg.generated
	 */
	public void setLocalwiningrank(String localwiningrank) {
		this.localwiningrank = localwiningrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.local2winingrank
	 * @return  the value of public.rec_race_13.local2winingrank
	 * @mbg.generated
	 */
	public String getLocal2winingrank() {
		return local2winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.local2winingrank
	 * @param local2winingrank  the value for public.rec_race_13.local2winingrank
	 * @mbg.generated
	 */
	public void setLocal2winingrank(String local2winingrank) {
		this.local2winingrank = local2winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.local3winingrank
	 * @return  the value of public.rec_race_13.local3winingrank
	 * @mbg.generated
	 */
	public String getLocal3winingrank() {
		return local3winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.local3winingrank
	 * @param local3winingrank  the value for public.rec_race_13.local3winingrank
	 * @mbg.generated
	 */
	public void setLocal3winingrank(String local3winingrank) {
		this.local3winingrank = local3winingrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.motor2rank
	 * @return  the value of public.rec_race_13.motor2rank
	 * @mbg.generated
	 */
	public String getMotor2rank() {
		return motor2rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.motor2rank
	 * @param motor2rank  the value for public.rec_race_13.motor2rank
	 * @mbg.generated
	 */
	public void setMotor2rank(String motor2rank) {
		this.motor2rank = motor2rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.motor3rank
	 * @return  the value of public.rec_race_13.motor3rank
	 * @mbg.generated
	 */
	public String getMotor3rank() {
		return motor3rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.motor3rank
	 * @param motor3rank  the value for public.rec_race_13.motor3rank
	 * @mbg.generated
	 */
	public void setMotor3rank(String motor3rank) {
		this.motor3rank = motor3rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.startexhibitrank
	 * @return  the value of public.rec_race_13.startexhibitrank
	 * @mbg.generated
	 */
	public String getStartexhibitrank() {
		return startexhibitrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.startexhibitrank
	 * @param startexhibitrank  the value for public.rec_race_13.startexhibitrank
	 * @mbg.generated
	 */
	public void setStartexhibitrank(String startexhibitrank) {
		this.startexhibitrank = startexhibitrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.exhibitrank
	 * @return  the value of public.rec_race_13.exhibitrank
	 * @mbg.generated
	 */
	public String getExhibitrank() {
		return exhibitrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.exhibitrank
	 * @param exhibitrank  the value for public.rec_race_13.exhibitrank
	 * @mbg.generated
	 */
	public void setExhibitrank(String exhibitrank) {
		this.exhibitrank = exhibitrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.averagestartrank
	 * @return  the value of public.rec_race_13.averagestartrank
	 * @mbg.generated
	 */
	public String getAveragestartrank() {
		return averagestartrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.averagestartrank
	 * @param averagestartrank  the value for public.rec_race_13.averagestartrank
	 * @mbg.generated
	 */
	public void setAveragestartrank(String averagestartrank) {
		this.averagestartrank = averagestartrank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.fixedentrance
	 * @return  the value of public.rec_race_13.fixedentrance
	 * @mbg.generated
	 */
	public String getFixedentrance() {
		return fixedentrance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.fixedentrance
	 * @param fixedentrance  the value for public.rec_race_13.fixedentrance
	 * @mbg.generated
	 */
	public void setFixedentrance(String fixedentrance) {
		this.fixedentrance = fixedentrance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.racetype
	 * @return  the value of public.rec_race_13.racetype
	 * @mbg.generated
	 */
	public String getRacetype() {
		return racetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.racetype
	 * @param racetype  the value for public.rec_race_13.racetype
	 * @mbg.generated
	 */
	public void setRacetype(String racetype) {
		this.racetype = racetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.wakulevellist
	 * @return  the value of public.rec_race_13.wakulevellist
	 * @mbg.generated
	 */
	public String getWakulevellist() {
		return wakulevellist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.wakulevellist
	 * @param wakulevellist  the value for public.rec_race_13.wakulevellist
	 * @mbg.generated
	 */
	public void setWakulevellist(String wakulevellist) {
		this.wakulevellist = wakulevellist;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.alevelcount
	 * @return  the value of public.rec_race_13.alevelcount
	 * @mbg.generated
	 */
	public Short getAlevelcount() {
		return alevelcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.alevelcount
	 * @param alevelcount  the value for public.rec_race_13.alevelcount
	 * @mbg.generated
	 */
	public void setAlevelcount(Short alevelcount) {
		this.alevelcount = alevelcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column public.rec_race_13.femalecount
	 * @return  the value of public.rec_race_13.femalecount
	 * @mbg.generated
	 */
	public Short getFemalecount() {
		return femalecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column public.rec_race_13.femalecount
	 * @param femalecount  the value for public.rec_race_13.femalecount
	 * @mbg.generated
	 */
	public void setFemalecount(Short femalecount) {
		this.femalecount = femalecount;
	}
}