package com.pengkong.boatrace.mybatis.client;

import com.pengkong.boatrace.mybatis.entity.RecRace13;
import com.pengkong.boatrace.mybatis.entity.RecRace13Example;
import java.util.List;

public interface RecRace13Mapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_race_13
	 * @mbg.generated
	 */
	int deleteByExample(RecRace13Example example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_race_13
	 * @mbg.generated
	 */
	int insert(RecRace13 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_race_13
	 * @mbg.generated
	 */
	int insertSelective(RecRace13 record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table public.rec_race_13
	 * @mbg.generated
	 */
	List<RecRace13> selectByExample(RecRace13Example example);
}